/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.7
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQtStackedBars3D.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtStackedBars3D.h"

#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qabstractseries3d.sip"
#include <QAbstractSeries3D.h>
#line 26 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qbarseries3d.sip"
#include <QBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qbardataitem3d.sip"
#include <QBarDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qbardataproxy3d.sip"
#include <QBarDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qcategoryaxis3d.sip"
#include <QCategoryAxis3D.h>
#line 26 "sip/QtStackedBars3D/qcustomitem3d.sip"
#include <QCustomItem3D.h>
#line 26 "sip/QtStackedBars3D/qcustomlabel3d.sip"
#include <QCustomLabel3D.h>
#line 26 "sip/QtStackedBars3D/qsurfaceseries3d.sip"
#include <QSurfaceSeries3D.h>
#line 26 "sip/QtStackedBars3D/qsurfacedataitem3d.sip"
#include <QSurfaceDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qsurfacedataproxy3d.sip"
#include <QSurfaceDataProxy3D.h>
#line 35 "sip/QtStackedBars3D/qsurfacedataproxy3d.sip"
#include <QSurfaceDataProxy3D.h>
#line 71 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"

#line 28 "/usr/share/sip/PyQt5/QtCore/qobject.sip"
#include <qobject.h>
#line 75 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qabstractseries3d.sip"
#include <QAbstractSeries3D.h>
#line 26 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qbarseries3d.sip"
#include <QBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qbardataitem3d.sip"
#include <QBarDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qbardataproxy3d.sip"
#include <QBarDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qcategoryaxis3d.sip"
#include <QCategoryAxis3D.h>
#line 26 "sip/QtStackedBars3D/qcustomitem3d.sip"
#include <QCustomItem3D.h>
#line 26 "sip/QtStackedBars3D/qcustomlabel3d.sip"
#include <QCustomLabel3D.h>
#line 26 "sip/QtStackedBars3D/qsurfaceseries3d.sip"
#include <QSurfaceSeries3D.h>
#line 32 "sip/QtStackedBars3D/qsurfaceseries3d.sip"
#include <QSurfaceSeries3D.h>
#line 116 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qabstractseries3d.sip"
#include <QAbstractSeries3D.h>
#line 26 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qbarseries3d.sip"
#include <QBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qbardataitem3d.sip"
#include <QBarDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qbardataproxy3d.sip"
#include <QBarDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qcategoryaxis3d.sip"
#include <QCategoryAxis3D.h>
#line 26 "sip/QtStackedBars3D/qcustomitem3d.sip"
#include <QCustomItem3D.h>
#line 26 "sip/QtStackedBars3D/qcustomlabel3d.sip"
#include <QCustomLabel3D.h>
#line 26 "sip/QtStackedBars3D/qsurfaceseries3d.sip"
#include <QSurfaceSeries3D.h>
#line 26 "sip/QtStackedBars3D/qsurfacedataitem3d.sip"
#include <QSurfaceDataItem3D.h>
#line 32 "sip/QtStackedBars3D/qsurfacedataitem3d.sip"
#include <QSurfaceDataItem3D.h>
#line 159 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qpoint.sip"
#include <qpoint.h>
#line 162 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 37 "sip/QtStackedBars3D/qlist.sip"
#include <qlist.h>
#include <qvector.h>
#line 166 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 28 "/usr/share/sip/PyQt5/QtCore/qpycore_qvector.sip"
#include <qvector.h>
#line 169 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qabstractseries3d.sip"
#include <QAbstractSeries3D.h>
#line 26 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 32 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 196 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 199 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 202 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 247 "/usr/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 205 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 235 "/usr/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 208 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 27 "/usr/share/sip/PyQt5/QtCore/qstring.sip"
#include <qstring.h>
#line 211 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qvariant.sip"
#include <qvariant.h>
#line 214 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 38 "/usr/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 217 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 30 "/usr/share/sip/PyQt5/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 220 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 149 "/usr/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 223 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 226 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qthread.sip"
#include <qthread.h>
#line 229 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 232 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qregexp.sip"
#include <qregexp.h>
#line 235 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 238 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 241 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQSurfaceDataProxy3D.cpp"


class sipQtStackedBar3DVis_QSurfaceDataProxy3D : public  ::QtStackedBar3DVis::QSurfaceDataProxy3D
{
public:
    sipQtStackedBar3DVis_QSurfaceDataProxy3D( ::QObject*);
    virtual ~sipQtStackedBar3DVis_QSurfaceDataProxy3D();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void disconnectNotify(const  ::QMetaMethod&);
    void connectNotify(const  ::QMetaMethod&);
    void customEvent( ::QEvent*);
    void childEvent( ::QChildEvent*);
    void timerEvent( ::QTimerEvent*);
    bool eventFilter( ::QObject*, ::QEvent*);
    bool event( ::QEvent*);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQtStackedBar3DVis_QSurfaceDataProxy3D(const sipQtStackedBar3DVis_QSurfaceDataProxy3D &);
    sipQtStackedBar3DVis_QSurfaceDataProxy3D &operator = (const sipQtStackedBar3DVis_QSurfaceDataProxy3D &);

    char sipPyMethods[7];
};

sipQtStackedBar3DVis_QSurfaceDataProxy3D::sipQtStackedBar3DVis_QSurfaceDataProxy3D( ::QObject*a0):  ::QtStackedBar3DVis::QSurfaceDataProxy3D(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQtStackedBar3DVis_QSurfaceDataProxy3D::~sipQtStackedBar3DVis_QSurfaceDataProxy3D()
{
    sipInstanceDestroyed(sipPySelf);
}

const QMetaObject *sipQtStackedBar3DVis_QSurfaceDataProxy3D::metaObject() const
{
    if (sipGetInterpreter())
        return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : sip_QtStackedBars3D_qt_metaobject(sipPySelf,sipType_QtStackedBar3DVis_QSurfaceDataProxy3D);

    return  ::QtStackedBar3DVis::QSurfaceDataProxy3D::metaObject();
}

int sipQtStackedBar3DVis_QSurfaceDataProxy3D::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id =  ::QtStackedBar3DVis::QSurfaceDataProxy3D::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_QtStackedBars3D_qt_metacall(sipPySelf,sipType_QtStackedBar3DVis_QSurfaceDataProxy3D,_c,_id,_a);

    return _id;
}

void *sipQtStackedBar3DVis_QSurfaceDataProxy3D::qt_metacast(const char *_clname)
{
    void *sipCpp;

    return (sip_QtStackedBars3D_qt_metacast(sipPySelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, _clname, &sipCpp) ? sipCpp :  ::QtStackedBar3DVis::QSurfaceDataProxy3D::qt_metacast(_clname));
}

void sipQtStackedBar3DVis_QSurfaceDataProxy3D::disconnectNotify(const  ::QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QSurfaceDataProxy3D::disconnectNotify(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_20(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QMetaMethod&);

    sipVH_QtStackedBars3D_20(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QSurfaceDataProxy3D::connectNotify(const  ::QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QSurfaceDataProxy3D::connectNotify(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_20(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QMetaMethod&);

    sipVH_QtStackedBars3D_20(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QSurfaceDataProxy3D::customEvent( ::QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QSurfaceDataProxy3D::customEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_19(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QEvent*);

    sipVH_QtStackedBars3D_19(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QSurfaceDataProxy3D::childEvent( ::QChildEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QSurfaceDataProxy3D::childEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_18(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QChildEvent*);

    sipVH_QtStackedBars3D_18(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QSurfaceDataProxy3D::timerEvent( ::QTimerEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QSurfaceDataProxy3D::timerEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_17(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QTimerEvent*);

    sipVH_QtStackedBars3D_17(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

bool sipQtStackedBar3DVis_QSurfaceDataProxy3D::eventFilter( ::QObject*a0, ::QEvent*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return  ::QtStackedBar3DVis::QSurfaceDataProxy3D::eventFilter(a0,a1);

    extern bool sipVH_QtStackedBars3D_16(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QObject*, ::QEvent*);

    return sipVH_QtStackedBars3D_16(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0, a1);
}

bool sipQtStackedBar3DVis_QSurfaceDataProxy3D::event( ::QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return  ::QtStackedBar3DVis::QSurfaceDataProxy3D::event(a0);

    extern bool sipVH_QtStackedBars3D_15(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QEvent*);

    return sipVH_QtStackedBars3D_15(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_rowCount, "rowCount(self) -> int");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_rowCount(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_rowCount(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->rowCount();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_rowCount, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_rowCount);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_columnCount, "columnCount(self) -> int");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_columnCount(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_columnCount(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp))
        {
            int sipRes;

            sipRes = sipCpp->columnCount();

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_columnCount, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_columnCount);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_array, "array(self) -> object");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_array(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_array(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp))
        {
            const  ::QtStackedBar3DVis::QSurfaceDataArray3D*sipRes;

            sipRes = sipCpp->array();

            return sipConvertFromType(const_cast< ::QtStackedBar3DVis::QSurfaceDataArray3D *>(sipRes),sipType_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_array, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_array);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_resetArray, "resetArray(self, object)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_resetArray(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_resetArray(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QSurfaceDataArray3D* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ2", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, sipType_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,&a0, &a0State))
        {
            sipCpp->resetArray(a0);
            sipReleaseType(a0,sipType_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_resetArray, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_resetArray);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_setRow, "setRow(self, int, object)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_setRow(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_setRow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
         ::QtStackedBar3DVis::QSurfaceDataRow3D* a1;
        int a1State = 0;
         ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ2", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, &a0, sipType_QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,&a1, &a1State))
        {
            sipCpp->setRow(a0,a1);
            sipReleaseType(a1,sipType_QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,a1State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_setRow, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_setRow);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_setRows, "setRows(self, int, object)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_setRows(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_setRows(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const  ::QtStackedBar3DVis::QSurfaceDataArray3D* a1;
        int a1State = 0;
         ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ1", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, &a0, sipType_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,&a1, &a1State))
        {
            sipCpp->setRows(a0,*a1);
            sipReleaseType(const_cast< ::QtStackedBar3DVis::QSurfaceDataArray3D *>(a1),sipType_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,a1State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_setRows, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_setRows);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_setItem, "setItem(self, int, int, QtStackedBar3DVis.QSurfaceDataItem3D)\n"
"setItem(self, QPoint, QtStackedBar3DVis.QSurfaceDataItem3D)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_setItem(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_setItem(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        int a1;
        const  ::QtStackedBar3DVis::QSurfaceDataItem3D* a2;
         ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiiJ9", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, &a0, &a1, sipType_QtStackedBar3DVis_QSurfaceDataItem3D, &a2))
        {
            sipCpp->setItem(a0,a1,*a2);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    {
        const  ::QPoint* a0;
        const  ::QtStackedBar3DVis::QSurfaceDataItem3D* a1;
         ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9J9", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, sipType_QPoint, &a0, sipType_QtStackedBar3DVis_QSurfaceDataItem3D, &a1))
        {
            sipCpp->setItem(*a0,*a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_setItem, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_setItem);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_addRow, "addRow(self, object) -> int");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_addRow(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_addRow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QSurfaceDataRow3D* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ2", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, sipType_QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,&a0, &a0State))
        {
            int sipRes;

            sipRes = sipCpp->addRow(a0);
            sipReleaseType(a0,sipType_QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,a0State);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_addRow, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_addRow);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_addRows, "addRows(self, object) -> int");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_addRows(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_addRows(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QSurfaceDataArray3D* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, sipType_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,&a0, &a0State))
        {
            int sipRes;

            sipRes = sipCpp->addRows(*a0);
            sipReleaseType(const_cast< ::QtStackedBar3DVis::QSurfaceDataArray3D *>(a0),sipType_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,a0State);

            return SIPLong_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_addRows, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_addRows);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRow, "insertRow(self, int, object)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRow(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRow(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
         ::QtStackedBar3DVis::QSurfaceDataRow3D* a1;
        int a1State = 0;
         ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ2", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, &a0, sipType_QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,&a1, &a1State))
        {
            sipCpp->insertRow(a0,a1);
            sipReleaseType(a1,sipType_QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,a1State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_insertRow, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRow);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRows, "insertRows(self, int, object)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRows(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRows(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        const  ::QtStackedBar3DVis::QSurfaceDataArray3D* a1;
        int a1State = 0;
         ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ1", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, &a0, sipType_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,&a1, &a1State))
        {
            sipCpp->insertRows(a0,*a1);
            sipReleaseType(const_cast< ::QtStackedBar3DVis::QSurfaceDataArray3D *>(a1),sipType_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,a1State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_insertRows, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRows);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_removeRows, "removeRows(self, int, int)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_removeRows(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_removeRows(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        int a1;
         ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bii", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, &a0, &a1))
        {
            sipCpp->removeRows(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_removeRows, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_removeRows);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_series, "series(self) -> QtStackedBar3DVis.QSurfaceSeries3D");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_series(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_series(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp))
        {
             ::QtStackedBar3DVis::QSurfaceSeries3D*sipRes;

            sipRes = sipCpp->series();

            return sipConvertFromType(sipRes,sipType_QtStackedBar3DVis_QSurfaceSeries3D,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_series, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_series);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_itemAt, "itemAt(self, int, int) -> QtStackedBar3DVis.QSurfaceDataItem3D\n"
"itemAt(self, QPoint) -> QtStackedBar3DVis.QSurfaceDataItem3D");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_itemAt(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QSurfaceDataProxy3D_itemAt(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
        int a1;
        const  ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bii", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, &a0, &a1))
        {
            const  ::QtStackedBar3DVis::QSurfaceDataItem3D*sipRes;

            sipRes = sipCpp->itemAt(a0,a1);

            return sipConvertFromType(const_cast< ::QtStackedBar3DVis::QSurfaceDataItem3D *>(sipRes),sipType_QtStackedBar3DVis_QSurfaceDataItem3D,NULL);
        }
    }

    {
        const  ::QPoint* a0;
        const  ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QtStackedBar3DVis_QSurfaceDataProxy3D, &sipCpp, sipType_QPoint, &a0))
        {
            const  ::QtStackedBar3DVis::QSurfaceDataItem3D*sipRes;

            sipRes = sipCpp->itemAt(*a0);

            return sipConvertFromType(const_cast< ::QtStackedBar3DVis::QSurfaceDataItem3D *>(sipRes),sipType_QtStackedBar3DVis_QSurfaceDataItem3D,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QSurfaceDataProxy3D, sipName_itemAt, doc_QtStackedBar3DVis_QSurfaceDataProxy3D_itemAt);

    return NULL;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_QtStackedBar3DVis_QSurfaceDataProxy3D(void *, const sipTypeDef *);}
static void *cast_QtStackedBar3DVis_QSurfaceDataProxy3D(void *sipCppV, const sipTypeDef *targetType)
{
     ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QSurfaceDataProxy3D *>(sipCppV);

    if (targetType == sipType_QtStackedBar3DVis_QAbstractDataProxy3D)
        return static_cast< ::QtStackedBar3DVis::QAbstractDataProxy3D *>(sipCpp);

    if (targetType == sipType_QObject)
        return static_cast< ::QObject *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_QtStackedBar3DVis_QSurfaceDataProxy3D(void *, int);}
static void release_QtStackedBar3DVis_QSurfaceDataProxy3D(void *sipCppV, int)
{
     ::QtStackedBar3DVis::QSurfaceDataProxy3D *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QSurfaceDataProxy3D *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QtStackedBar3DVis_QSurfaceDataProxy3D(sipSimpleWrapper *);}
static void dealloc_QtStackedBar3DVis_QSurfaceDataProxy3D(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipQtStackedBar3DVis_QSurfaceDataProxy3D *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_QtStackedBar3DVis_QSurfaceDataProxy3D(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_QtStackedBar3DVis_QSurfaceDataProxy3D(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QtStackedBar3DVis_QSurfaceDataProxy3D(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQtStackedBar3DVis_QSurfaceDataProxy3D *sipCpp = 0;

    {
         ::QObject* a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JH", sipType_QObject, &a0, sipOwner))
        {
            sipCpp = new sipQtStackedBar3DVis_QSurfaceDataProxy3D(a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QtStackedBar3DVis_QSurfaceDataProxy3D[] = {{15, 255, 1}};


static PyMethodDef methods_QtStackedBar3DVis_QSurfaceDataProxy3D[] = {
    {SIP_MLNAME_CAST(sipName_addRow), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_addRow, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_addRow)},
    {SIP_MLNAME_CAST(sipName_addRows), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_addRows, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_addRows)},
    {SIP_MLNAME_CAST(sipName_array), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_array, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_array)},
    {SIP_MLNAME_CAST(sipName_columnCount), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_columnCount, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_columnCount)},
    {SIP_MLNAME_CAST(sipName_insertRow), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRow, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRow)},
    {SIP_MLNAME_CAST(sipName_insertRows), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRows, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_insertRows)},
    {SIP_MLNAME_CAST(sipName_itemAt), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_itemAt, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_itemAt)},
    {SIP_MLNAME_CAST(sipName_removeRows), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_removeRows, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_removeRows)},
    {SIP_MLNAME_CAST(sipName_resetArray), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_resetArray, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_resetArray)},
    {SIP_MLNAME_CAST(sipName_rowCount), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_rowCount, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_rowCount)},
    {SIP_MLNAME_CAST(sipName_series), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_series, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_series)},
    {SIP_MLNAME_CAST(sipName_setItem), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_setItem, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_setItem)},
    {SIP_MLNAME_CAST(sipName_setRow), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_setRow, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_setRow)},
    {SIP_MLNAME_CAST(sipName_setRows), meth_QtStackedBar3DVis_QSurfaceDataProxy3D_setRows, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QSurfaceDataProxy3D_setRows)}
};

PyDoc_STRVAR(doc_QtStackedBar3DVis_QSurfaceDataProxy3D, "\1QtStackedBar3DVis.QSurfaceDataProxy3D(parent: QObject = None)");


/* Define this type's signals. */
static const pyqt5QtSignal signals_QtStackedBar3DVis_QSurfaceDataProxy3D[] = {
    {"seriesChanged(QSurfaceSeries3D*)", "\1seriesChanged(self, QtStackedBar3DVis.QSurfaceSeries3D)", 0, 0},
    {"columnCountChanged(int)", "\1columnCountChanged(self, int)", 0, 0},
    {"rowCountChanged(int)", "\1rowCountChanged(self, int)", 0, 0},
    {"itemChanged(int,int)", "\1itemChanged(self, int, int)", 0, 0},
    {"rowsInserted(int,int)", "\1rowsInserted(self, int, int)", 0, 0},
    {"rowsRemoved(int,int)", "\1rowsRemoved(self, int, int)", 0, 0},
    {"rowsChanged(int,int)", "\1rowsChanged(self, int, int)", 0, 0},
    {"rowsAdded(int,int)", "\1rowsAdded(self, int, int)", 0, 0},
    {"arrayReset()", "\1arrayReset(self)", 0, 0},
    {0, 0, 0, 0}
};


static pyqt5ClassPluginDef plugin_QtStackedBar3DVis_QSurfaceDataProxy3D = {
    & ::QtStackedBar3DVis::QSurfaceDataProxy3D::staticMetaObject,
    0,
    signals_QtStackedBar3DVis_QSurfaceDataProxy3D,
    0
};


sipClassTypeDef sipTypeDef_QtStackedBars3D_QtStackedBar3DVis_QSurfaceDataProxy3D = {
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_LIMITED_API|SIP_TYPE_CLASS,
        sipNameNr_QtStackedBar3DVis__QSurfaceDataProxy3D,
        {0},
        &plugin_QtStackedBar3DVis_QSurfaceDataProxy3D
    },
    {
        sipNameNr_QSurfaceDataProxy3D,
        {11, 255, 0},
        14, methods_QtStackedBar3DVis_QSurfaceDataProxy3D,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QtStackedBar3DVis_QSurfaceDataProxy3D,
    -1,
    -1,
    supers_QtStackedBar3DVis_QSurfaceDataProxy3D,
    0,
    init_type_QtStackedBar3DVis_QSurfaceDataProxy3D,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QtStackedBar3DVis_QSurfaceDataProxy3D,
    0,
    0,
    0,
    release_QtStackedBar3DVis_QSurfaceDataProxy3D,
    cast_QtStackedBar3DVis_QSurfaceDataProxy3D,
    0,
    0,
    0,
    0,
    0,
    0
};
