/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.12
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQtStackedBars3D.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtStackedBars3D.h"

#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 32 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 49 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractGraph3DSelectionFlags.cpp"

#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 32 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 73 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractGraph3DSelectionFlags.cpp"


extern "C" {static long slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___hash__(PyObject *);}
static long slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___hash__(PyObject *sipSelf)
{
     ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags));

    if (!sipCpp)
        return 0;


    {
        {
            long sipRes = 0;

#line 116 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qglobal.sip"
        sipRes = sipCpp->operator QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags::Int();
#line 91 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractGraph3DSelectionFlags.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static int slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___bool__(PyObject *);}
static int slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___bool__(PyObject *sipSelf)
{
     ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags));

    if (!sipCpp)
        return -1;


    {
        {
            int sipRes = 0;

#line 111 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags::Int() != 0);
#line 116 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractGraph3DSelectionFlags.cpp"

            return sipRes;
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___ne__(PyObject *,PyObject *);}
static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___ne__(PyObject *sipSelf,PyObject *sipArg)
{
     ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags, &a0, &a0State))
        {
            bool sipRes = 0;

#line 106 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags::Int() != a0->operator QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags::Int());
#line 146 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractGraph3DSelectionFlags.cpp"
            sipReleaseType(const_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(a0),sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtStackedBars3D, ne_slot, sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags, sipSelf, sipArg);
}


extern "C" {static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___eq__(PyObject *,PyObject *);}
static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___eq__(PyObject *sipSelf,PyObject *sipArg)
{
     ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags* a0;
        int a0State = 0;

        if (sipParseArgs(&sipParseErr, sipArg, "1J1", sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags, &a0, &a0State))
        {
            bool sipRes = 0;

#line 101 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qglobal.sip"
        sipRes = (sipCpp->operator QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags::Int() == a0->operator QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags::Int());
#line 182 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractGraph3DSelectionFlags.cpp"
            sipReleaseType(const_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(a0),sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,a0State);

            return PyBool_FromLong(sipRes);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtStackedBars3D, eq_slot, sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags, sipSelf, sipArg);
}


extern "C" {static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___ixor__(PyObject *,PyObject *);}
static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___ixor__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
#line 95 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qglobal.sip"
        *sipCpp = QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags(*sipCpp ^ a0);
#line 221 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractGraph3DSelectionFlags.cpp"

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___xor__(PyObject *,PyObject *);}
static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___xor__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags, &a0, &a0State, &a1))
        {
             ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags*sipRes;

            sipRes = new  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags((*a0 ^ a1));
            sipReleaseType(a0,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,a0State);

            return sipConvertFromNewType(sipRes,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtStackedBars3D, xor_slot, NULL, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___ior__(PyObject *,PyObject *);}
static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___ior__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
#line 89 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qglobal.sip"
        *sipCpp = QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags(*sipCpp | a0);
#line 293 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractGraph3DSelectionFlags.cpp"

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___or__(PyObject *,PyObject *);}
static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___or__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags, &a0, &a0State, &a1))
        {
             ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags*sipRes;

            sipRes = new  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags((*a0 | a1));
            sipReleaseType(a0,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,a0State);

            return sipConvertFromNewType(sipRes,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtStackedBars3D, or_slot, NULL, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___iand__(PyObject *,PyObject *);}
static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___iand__(PyObject *sipSelf,PyObject *sipArg)
{
    if (!PyObject_TypeCheck(sipSelf, sipTypeAsPyTypeObject(sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags)))
    {
        Py_INCREF(Py_NotImplemented);
        return Py_NotImplemented;
    }

     ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags));

    if (!sipCpp)
        return 0;

    PyObject *sipParseErr = NULL;

    {
        int a0;

        if (sipParseArgs(&sipParseErr, sipArg, "1i", &a0))
        {
            sipCpp-> ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags::operator&=(a0);

            Py_INCREF(sipSelf);
            return sipSelf;
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    PyErr_Clear();

    Py_INCREF(Py_NotImplemented);
    return Py_NotImplemented;
}


extern "C" {static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___and__(PyObject *,PyObject *);}
static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___and__(PyObject *sipArg0,PyObject *sipArg1)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags* a0;
        int a0State = 0;
        int a1;

        if (sipParsePair(&sipParseErr, sipArg0, sipArg1, "J1i", sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags, &a0, &a0State, &a1))
        {
             ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags*sipRes;

            sipRes = new  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags((*a0 & a1));
            sipReleaseType(a0,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,a0State);

            return sipConvertFromNewType(sipRes,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,NULL);
        }
    }

    Py_XDECREF(sipParseErr);

    if (sipParseErr == Py_None)
        return NULL;

    return sipPySlotExtend(&sipModuleAPI_QtStackedBars3D, and_slot, NULL, sipArg0, sipArg1);
}


extern "C" {static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___invert__(PyObject *);}
static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___invert__(PyObject *sipSelf)
{
     ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags));

    if (!sipCpp)
        return 0;


    {
        {
             ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags*sipRes;

            sipRes = new  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags(~(*sipCpp));

            return sipConvertFromNewType(sipRes,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,NULL);
        }
    }

    return 0;
}


extern "C" {static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___int__(PyObject *);}
static PyObject *slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___int__(PyObject *sipSelf)
{
     ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipGetCppPtr((sipSimpleWrapper *)sipSelf,sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags));

    if (!sipCpp)
        return 0;


    {
        {
            int sipRes;

            sipRes = *sipCpp;

            return SIPLong_FromLong(sipRes);
        }
    }

    return 0;
}


/* Call the instance's destructor. */
extern "C" {static void release_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(void *, int);}
static void release_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(void *sipCppV, int)
{
    delete reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipCppV);
}


extern "C" {static void assign_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(void *, SIP_SSIZE_T, void *);}
static void assign_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(void *sipDst, SIP_SSIZE_T sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipSrc);
}


extern "C" {static void *array_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(SIP_SSIZE_T);}
static void *array_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(SIP_SSIZE_T sipNrElem)
{
    return new  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags[sipNrElem];
}


extern "C" {static void *copy_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(const void *, SIP_SSIZE_T);}
static void *copy_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags(reinterpret_cast<const  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(sipSimpleWrapper *);}
static void dealloc_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(sipGetAddress(sipSelf), 0);
    }
}


extern "C" {static void *init_type_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
     ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            sipCpp = new  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags();

            return sipCpp;
        }
    }

    {
        int a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "i", &a0))
        {
            sipCpp = new  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags(a0);

            return sipCpp;
        }
    }

    {
        const  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags* a0;
        int a0State = 0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J1", sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags, &a0, &a0State))
        {
            sipCpp = new  ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags(*a0);
            sipReleaseType(const_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(a0),sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,a0State);

            return sipCpp;
        }
    }

    return NULL;
}


extern "C" {static int convertTo_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(PyObject *, void **, int *, PyObject *);}
static int convertTo_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
     ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags **sipCppPtr = reinterpret_cast< ::QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags **>(sipCppPtrV);

#line 121 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qglobal.sip"
// Allow an instance of the base enum whenever a QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags is expected.

if (sipIsErr == NULL)
    return (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlag)) ||
            sipCanConvertToType(sipPy, sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags, SIP_NO_CONVERTORS));

if (PyObject_TypeCheck(sipPy, sipTypeAsPyTypeObject(sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlag)))
{
    *sipCppPtr = new QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags(int(SIPLong_AsLong(sipPy)));

    return sipGetState(sipTransferObj);
}

*sipCppPtr = reinterpret_cast<QtStackedBar3DVis::QAbstractGraph3D::SelectionFlags *>(sipConvertToType(sipPy, sipType_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags, sipTransferObj, SIP_NO_CONVERTORS, 0, sipIsErr));

return 0;
#line 561 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractGraph3DSelectionFlags.cpp"
}


/* Define this type's Python slots. */
static sipPySlotDef slots_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags[] = {
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___hash__, hash_slot},
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___bool__, bool_slot},
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___ne__, ne_slot},
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___eq__, eq_slot},
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___ixor__, ixor_slot},
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___xor__, xor_slot},
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___ior__, ior_slot},
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___or__, or_slot},
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___iand__, iand_slot},
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___and__, and_slot},
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___invert__, invert_slot},
    {(void *)slot_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags___int__, int_slot},
    {0, (sipPySlotType)0}
};

PyDoc_STRVAR(doc_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags, "\1QtStackedBar3DVis.QAbstractGraph3D.SelectionFlags()\n"
"QtStackedBar3DVis.QAbstractGraph3D.SelectionFlags(Union[QtStackedBar3DVis.QAbstractGraph3D.SelectionFlags, QtStackedBar3DVis.QAbstractGraph3D.SelectionFlag])\n"
"QtStackedBar3DVis.QAbstractGraph3D.SelectionFlags(QtStackedBar3DVis.QAbstractGraph3D.SelectionFlags)");


static pyqt5ClassPluginDef plugin_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags = {
    0,
    1,
    0,
    0
};


sipClassTypeDef sipTypeDef_QtStackedBars3D_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags = {
    {
        -1,
        0,
        0,
        SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QtStackedBar3DVis__QAbstractGraph3D__SelectionFlags,
        {0},
        &plugin_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags
    },
    {
        sipNameNr_SelectionFlags,
        {20, 255, 0},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,
    -1,
    sipNameNr_sip_simplewrapper,
    0,
    slots_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,
    init_type_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,
    assign_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,
    array_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,
    copy_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,
    release_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,
    0,
    convertTo_QtStackedBar3DVis_QAbstractGraph3D_SelectionFlags,
    0,
    0,
    0,
    0,
    0
};
