/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.12
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQtStackedBars3D.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtStackedBars3D.h"

#line 38 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 29 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQList0100QColor.cpp"

#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qcolor.sip"
#include <qcolor.h>
#line 33 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQList0100QColor.cpp"


extern "C" {static void assign_QList_0100QColor(void *, SIP_SSIZE_T, void *);}
static void assign_QList_0100QColor(void *sipDst, SIP_SSIZE_T sipDstIdx, void *sipSrc)
{
    reinterpret_cast<QList< ::QColor> *>(sipDst)[sipDstIdx] = *reinterpret_cast<QList< ::QColor> *>(sipSrc);
}


extern "C" {static void *array_QList_0100QColor(SIP_SSIZE_T);}
static void *array_QList_0100QColor(SIP_SSIZE_T sipNrElem)
{
    return new QList< ::QColor>[sipNrElem];
}


extern "C" {static void *copy_QList_0100QColor(const void *, SIP_SSIZE_T);}
static void *copy_QList_0100QColor(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QList< ::QColor>(reinterpret_cast<const QList< ::QColor> *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_QList_0100QColor(void *, int);}
static void release_QList_0100QColor(void *ptr, int)
{
    delete reinterpret_cast<QList< ::QColor> *>(ptr);
}



extern "C" {static int convertTo_QList_0100QColor(PyObject *, void **, int *, PyObject *);}
static int convertTo_QList_0100QColor(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QList< ::QColor> **sipCppPtr = reinterpret_cast<QList< ::QColor> **>(sipCppPtrV);

#line 68 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
    PyObject *iter = PyObject_GetIter(sipPy);

    if (!sipIsErr)
    {
        PyErr_Clear();
        Py_XDECREF(iter);

        return (iter
#if PY_MAJOR_VERSION < 3
                && !PyString_Check(sipPy)
#endif
                && !PyUnicode_Check(sipPy));
    }

    if (!iter)
    {
        *sipIsErr = 1;

        return 0;
    }

    QList<QColor> *ql = new QList<QColor>;
 
    for (Py_ssize_t i = 0; ; ++i)
    {
        PyErr_Clear();
        PyObject *itm = PyIter_Next(iter);

        if (!itm)
        {
            if (PyErr_Occurred())
            {
                delete ql;
                Py_DECREF(iter);
                *sipIsErr = 1;

                return 0;
            }

            break;
        }

        int state;
        QColor *t = reinterpret_cast<QColor *>(
                sipForceConvertToType(itm, sipType_QColor, sipTransferObj,
                        SIP_NOT_NONE, &state, sipIsErr));

        if (*sipIsErr)
        {
            PyErr_Format(PyExc_TypeError,
                    "index %zd has type '%s' but 'QColor' is expected", i,
                    sipPyTypeName(Py_TYPE(itm)));

            Py_DECREF(itm);
            delete ql;
            Py_DECREF(iter);

            return 0;
        }

        ql->append(*t);

        sipReleaseType(t, sipType_QColor, state);
        Py_DECREF(itm);
    }
 
    Py_DECREF(iter);

    *sipCppPtr = ql;
 
    return sipGetState(sipTransferObj);
#line 143 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQList0100QColor.cpp"
}


extern "C" {static PyObject *convertFrom_QList_0100QColor(void *, PyObject *);}
static PyObject *convertFrom_QList_0100QColor(void *sipCppV, PyObject *sipTransferObj)
{
   QList< ::QColor> *sipCpp = reinterpret_cast<QList< ::QColor> *>(sipCppV);

#line 42 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
    PyObject *l = PyList_New(sipCpp->size());

    if (!l)
        return 0;

    for (int i = 0; i < sipCpp->size(); ++i)
    {
        QColor *t = new QColor(sipCpp->at(i));
        PyObject *tobj = sipConvertFromNewType(t, sipType_QColor,
                sipTransferObj);

        if (!tobj)
        {
            delete t;
            Py_DECREF(l);

            return 0;
        }

        PyList_SetItem(l, i, tobj);
    }

    return l;
#line 176 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQList0100QColor.cpp"
}


sipMappedTypeDef sipTypeDef_QtStackedBars3D_QList_0100QColor = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_8849,     /* QList<QColor> */
        {0},
        0
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_QList_0100QColor,
    array_QList_0100QColor,
    copy_QList_0100QColor,
    release_QList_0100QColor,
    convertTo_QList_0100QColor,
    convertFrom_QList_0100QColor
};
