/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.7
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQtStackedBars3D.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtStackedBars3D.h"

#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qabstractseries3d.sip"
#include <QAbstractSeries3D.h>
#line 26 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 32 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 53 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"

#line 26 "/usr/share/sip/PyQt5/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 57 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 60 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 247 "/usr/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 63 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 235 "/usr/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 66 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 28 "/usr/share/sip/PyQt5/QtCore/qobject.sip"
#include <qobject.h>
#line 69 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 27 "/usr/share/sip/PyQt5/QtCore/qstring.sip"
#include <qstring.h>
#line 72 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qvariant.sip"
#include <qvariant.h>
#line 75 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 38 "/usr/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 78 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 30 "/usr/share/sip/PyQt5/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 81 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 149 "/usr/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 84 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 87 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qthread.sip"
#include <qthread.h>
#line 90 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 93 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qregexp.sip"
#include <qregexp.h>
#line 96 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 99 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"
#line 26 "/usr/share/sip/PyQt5/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 102 "/home/faichele/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQAbstractDataProxy3D.cpp"


PyDoc_STRVAR(doc_QtStackedBar3DVis_QAbstractDataProxy3D_type, "type(self) -> QtStackedBar3DVis.QAbstractDataProxy3D.DataType");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QAbstractDataProxy3D_type(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QAbstractDataProxy3D_type(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QAbstractDataProxy3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QAbstractDataProxy3D, &sipCpp))
        {
             ::QtStackedBar3DVis::QAbstractDataProxy3D::DataType sipRes;

            sipRes = sipCpp->type();

            return sipConvertFromEnum(static_cast<int>(sipRes), sipType_QtStackedBar3DVis_QAbstractDataProxy3D_DataType);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QAbstractDataProxy3D, sipName_type, doc_QtStackedBar3DVis_QAbstractDataProxy3D_type);

    return NULL;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_QtStackedBar3DVis_QAbstractDataProxy3D(void *, const sipTypeDef *);}
static void *cast_QtStackedBar3DVis_QAbstractDataProxy3D(void *sipCppV, const sipTypeDef *targetType)
{
     ::QtStackedBar3DVis::QAbstractDataProxy3D *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QAbstractDataProxy3D *>(sipCppV);

    if (targetType == sipType_QObject)
        return static_cast< ::QObject *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_QtStackedBar3DVis_QAbstractDataProxy3D(void *, int);}
static void release_QtStackedBar3DVis_QAbstractDataProxy3D(void *sipCppV, int)
{
     ::QtStackedBar3DVis::QAbstractDataProxy3D *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QAbstractDataProxy3D *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QtStackedBar3DVis_QAbstractDataProxy3D(sipSimpleWrapper *);}
static void dealloc_QtStackedBar3DVis_QAbstractDataProxy3D(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_QtStackedBar3DVis_QAbstractDataProxy3D(sipGetAddress(sipSelf), 0);
    }
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QtStackedBar3DVis_QAbstractDataProxy3D[] = {{4, 0, 1}};


static PyMethodDef methods_QtStackedBar3DVis_QAbstractDataProxy3D[] = {
    {SIP_MLNAME_CAST(sipName_type), meth_QtStackedBar3DVis_QAbstractDataProxy3D_type, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QAbstractDataProxy3D_type)}
};

static sipEnumMemberDef enummembers_QtStackedBar3DVis_QAbstractDataProxy3D[] = {
    {sipName_DataTypeBar, static_cast<int>( ::QtStackedBar3DVis::QAbstractDataProxy3D::DataTypeBar), 16},
    {sipName_DataTypeNone, static_cast<int>( ::QtStackedBar3DVis::QAbstractDataProxy3D::DataTypeNone), 16},
    {sipName_DataTypeScatter, static_cast<int>( ::QtStackedBar3DVis::QAbstractDataProxy3D::DataTypeScatter), 16},
    {sipName_DataTypeSurface, static_cast<int>( ::QtStackedBar3DVis::QAbstractDataProxy3D::DataTypeSurface), 16},
};


static pyqt5ClassPluginDef plugin_QtStackedBar3DVis_QAbstractDataProxy3D = {
    & ::QtStackedBar3DVis::QAbstractDataProxy3D::staticMetaObject,
    0,
    0,
    0
};


sipClassTypeDef sipTypeDef_QtStackedBars3D_QtStackedBar3DVis_QAbstractDataProxy3D = {
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_LIMITED_API|SIP_TYPE_CLASS,
        sipNameNr_QtStackedBar3DVis__QAbstractDataProxy3D,
        {0},
        &plugin_QtStackedBar3DVis_QAbstractDataProxy3D
    },
    {
        sipNameNr_QAbstractDataProxy3D,
        {11, 255, 0},
        1, methods_QtStackedBar3DVis_QAbstractDataProxy3D,
        4, enummembers_QtStackedBar3DVis_QAbstractDataProxy3D,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    0,
    -1,
    -1,
    supers_QtStackedBar3DVis_QAbstractDataProxy3D,
    0,
    0,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QtStackedBar3DVis_QAbstractDataProxy3D,
    0,
    0,
    0,
    release_QtStackedBar3DVis_QAbstractDataProxy3D,
    cast_QtStackedBar3DVis_QAbstractDataProxy3D,
    0,
    0,
    0,
    0,
    0,
    0
};
