/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.12
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQtStackedBars3D.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtStackedBars3D.h"

#line 37 "sip/QtStackedBars3D/qlist.sip"
#include <qlist.h>
#include <qvector.h>
#line 30 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQList0601QVector0100QtStackedBar3DVisQSurfaceDataItem3D.cpp"

#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qabstractseries3d.sip"
#include <QAbstractSeries3D.h>
#line 26 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qbarseries3d.sip"
#include <QBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qbardataitem3d.sip"
#include <QBarDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qbardataproxy3d.sip"
#include <QBarDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qcategoryaxis3d.sip"
#include <QCategoryAxis3D.h>
#line 26 "sip/QtStackedBars3D/qcustomitem3d.sip"
#include <QCustomItem3D.h>
#line 26 "sip/QtStackedBars3D/qcustomlabel3d.sip"
#include <QCustomLabel3D.h>
#line 26 "sip/QtStackedBars3D/qsurfaceseries3d.sip"
#include <QSurfaceSeries3D.h>
#line 26 "sip/QtStackedBars3D/qsurfacedataitem3d.sip"
#include <QSurfaceDataItem3D.h>
#line 32 "sip/QtStackedBars3D/qsurfacedataitem3d.sip"
#include <QSurfaceDataItem3D.h>
#line 74 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQList0601QVector0100QtStackedBar3DVisQSurfaceDataItem3D.cpp"


extern "C" {static void assign_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(void *, SIP_SSIZE_T, void *);}
static void assign_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(void *sipDst, SIP_SSIZE_T sipDstIdx, void *sipSrc)
{
    reinterpret_cast<QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D>*> *>(sipDst)[sipDstIdx] = *reinterpret_cast<QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D>*> *>(sipSrc);
}


extern "C" {static void *array_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(SIP_SSIZE_T);}
static void *array_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(SIP_SSIZE_T sipNrElem)
{
    return new QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D>*>[sipNrElem];
}


extern "C" {static void *copy_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(const void *, SIP_SSIZE_T);}
static void *copy_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D>*>(reinterpret_cast<const QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D>*> *>(sipSrc)[sipSrcIdx]);
}


/* Call the mapped type's destructor. */
extern "C" {static void release_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(void *, int);}
static void release_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(void *ptr, int)
{
    delete reinterpret_cast<QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D>*> *>(ptr);
}



extern "C" {static int convertTo_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(PyObject *, void **, int *, PyObject *);}
static int convertTo_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(PyObject *sipPy,void **sipCppPtrV,int *sipIsErr,PyObject *sipTransferObj)
{
    QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D>*> **sipCppPtr = reinterpret_cast<QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D>*> **>(sipCppPtrV);

#line 84 "sip/QtStackedBars3D/qlist.sip"
    PyObject *iter = PyObject_GetIter(sipPy);

    if (!sipIsErr)
    {
        Py_XDECREF(iter);

        return (iter
#if PY_MAJOR_VERSION < 3
                && !PyString_Check(sipPy)
#endif
                && !PyUnicode_Check(sipPy));
    }

    if (!iter)
    {
        *sipIsErr = 1;

        return 0;
    }

    QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D> *> *ql = new QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D> *>;
 
    for (SIP_SSIZE_T i = 0; ; ++i)
    {
        PyErr_Clear();
        PyObject *itm = PyIter_Next(iter);

        if (!itm)
        {
            if (PyErr_Occurred())
            {
                delete ql;
                Py_DECREF(iter);
                *sipIsErr = 1;

                return 0;
            }

            break;
        }

        PyObject *vec_iter = PyObject_GetIter(itm);

        if (!vec_iter)
        {
            PyErr_Format(PyExc_TypeError,
                    "index " SIP_SSIZE_T_FORMAT " is not iterable", i);

            Py_DECREF(itm);
            delete ql;
            Py_DECREF(iter);

            return 0;
        }

        QVector<QtStackedBar3DVis::QSurfaceDataItem3D> *qv = new QVector<QtStackedBar3DVis::QSurfaceDataItem3D>;

        ql->append(qv);

        for (SIP_SSIZE_T j = 0; ; ++j)
        {
            PyErr_Clear();
            PyObject *vec_itm = PyIter_Next(vec_iter);

            if (!vec_itm)
            {
                if (PyErr_Occurred())
                {
                    Py_DECREF(vec_iter);
                    delete ql;
                    Py_DECREF(iter);
                    *sipIsErr = 1;

                    return 0;
                }

                break;
            }

            int state;
            QtStackedBar3DVis::QSurfaceDataItem3D *t = reinterpret_cast<QtStackedBar3DVis::QSurfaceDataItem3D *>(
                    sipForceConvertToType(vec_itm, sipType_QtStackedBar3DVis_QSurfaceDataItem3D,
                            sipTransferObj, SIP_NOT_NONE, &state, sipIsErr));
 
            if (*sipIsErr)
            {
                PyErr_Format(PyExc_TypeError,
                        "index " SIP_SSIZE_T_FORMAT ", " SIP_SSIZE_T_FORMAT " has type '%s' but 'QtStackedBar3DVis::QSurfaceDataItem3D' is expected",
                        i, j, sipPyTypeName(Py_TYPE(itm)));

                Py_DECREF(vec_itm);
                Py_DECREF(vec_iter);

                Py_DECREF(itm);
                delete ql;
                Py_DECREF(iter);

                return 0;
            }

            qv->append(*t);

            sipReleaseType(t, sipType_QtStackedBar3DVis_QSurfaceDataItem3D, state);
            Py_DECREF(vec_itm);
        }

        Py_DECREF(vec_iter);

        Py_DECREF(itm);
    }

    Py_DECREF(iter);
 
    *sipCppPtr = ql;
 
    return sipGetState(sipTransferObj);
#line 229 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQList0601QVector0100QtStackedBar3DVisQSurfaceDataItem3D.cpp"
}


extern "C" {static PyObject *convertFrom_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(void *, PyObject *);}
static PyObject *convertFrom_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D(void *sipCppV, PyObject *sipTransferObj)
{
   QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D>*> *sipCpp = reinterpret_cast<QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D>*> *>(sipCppV);

#line 42 "sip/QtStackedBars3D/qlist.sip"
    PyObject *l = PyList_New(sipCpp->size());

    if (!l)
        return 0;

    for (int i = 0; i < sipCpp->size(); ++i)
    {
        QVector<QtStackedBar3DVis::QSurfaceDataItem3D> *t_vec = sipCpp->at(i);

        PyObject *v = PyList_New(t_vec->size());

        if (!v)
        {
            Py_DECREF(l);

            return 0;
        }

        PyList_SetItem(l, i, v);

        for (int j = 0; j < t_vec->size(); ++j)
        {
            QtStackedBar3DVis::QSurfaceDataItem3D *t = new QtStackedBar3DVis::QSurfaceDataItem3D(t_vec->at(i));
            PyObject *tobj = sipConvertFromType(t, sipType_QtStackedBar3DVis_QSurfaceDataItem3D,
                    sipTransferObj);

            if (!tobj)
            {
                delete t;
                Py_DECREF(l);

                return 0;
            }

            PyList_SetItem(v, j, tobj);
        }
    }

    return l;
#line 278 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQList0601QVector0100QtStackedBar3DVisQSurfaceDataItem3D.cpp"
}


sipMappedTypeDef sipTypeDef_QtStackedBars3D_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D = {
    {
        -1,
        0,
        0,
        SIP_TYPE_MAPPED,
        sipNameNr_0,     /* QList<QVector<QtStackedBar3DVis::QSurfaceDataItem3D>*> */
        {0},
        0
    },
    {
        -1,
        {0, 0, 1},
        0, 0,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
    },
    assign_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,
    array_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,
    copy_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,
    release_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,
    convertTo_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D,
    convertFrom_QList_0601QVector_0100QtStackedBar3DVis_QSurfaceDataItem3D
};
