/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.12
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQtStackedBars3D.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtStackedBars3D.h"

#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 32 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 33 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"

#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qsurfaceformat.sip"
#include <qsurfaceformat.h>
#line 37 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qwindow.sip"
#include <qwindow.h>
#line 40 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qabstractseries3d.sip"
#include <QAbstractSeries3D.h>
#line 26 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qbarseries3d.sip"
#include <QBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qbardataitem3d.sip"
#include <QBarDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qbardataproxy3d.sip"
#include <QBarDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbarseries3d.sip"
#include <QStackedBarSeries3D.h>
#line 32 "sip/QtStackedBars3D/qstackedbarseries3d.sip"
#include <QStackedBarSeries3D.h>
#line 77 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qabstractseries3d.sip"
#include <QAbstractSeries3D.h>
#line 26 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qbarseries3d.sip"
#include <QBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qbardataitem3d.sip"
#include <QBarDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qbardataproxy3d.sip"
#include <QBarDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbarseries3d.sip"
#include <QStackedBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbardataitem3d.sip"
#include <QStackedBarDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbardataproxy3d.sip"
#include <QStackedBarDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qcategoryaxis3d.sip"
#include <QCategoryAxis3D.h>
#line 26 "sip/QtStackedBars3D/qcustomitem3d.sip"
#include <QCustomItem3D.h>
#line 26 "sip/QtStackedBars3D/qcustomlabel3d.sip"
#include <QCustomLabel3D.h>
#line 26 "sip/QtStackedBars3D/qsurfaceseries3d.sip"
#include <QSurfaceSeries3D.h>
#line 26 "sip/QtStackedBars3D/qsurfacedataitem3d.sip"
#include <QSurfaceDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qsurfacedataproxy3d.sip"
#include <QSurfaceDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qtouchinputhandler3d.sip"
#include <QTouchInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qutils3d.sip"
#include <QUtilsGeneric.h>
#line 26 "sip/QtStackedBars3D/qvalueaxis3d.sip"
#include <QValueAxis3D.h>
#line 32 "sip/QtStackedBars3D/qvalueaxis3d.sip"
#include <QValueAxis3D.h>
#line 136 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qabstractseries3d.sip"
#include <QAbstractSeries3D.h>
#line 26 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qbarseries3d.sip"
#include <QBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qbardataitem3d.sip"
#include <QBarDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qbardataproxy3d.sip"
#include <QBarDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbarseries3d.sip"
#include <QStackedBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbardataitem3d.sip"
#include <QStackedBarDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbardataproxy3d.sip"
#include <QStackedBarDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qcategoryaxis3d.sip"
#include <QCategoryAxis3D.h>
#line 32 "sip/QtStackedBars3D/qcategoryaxis3d.sip"
#include <QCategoryAxis3D.h>
#line 179 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 97 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qsize.sip"
#include <qsize.h>
#line 182 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 149 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 185 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 32 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 206 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 149 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 209 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 30 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qvector3d.sip"
#include <qvector3d.h>
#line 212 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qlocale.sip"
#include <qlocale.h>
#line 215 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 149 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 218 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qabstractseries3d.sip"
#include <QAbstractSeries3D.h>
#line 26 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qbarseries3d.sip"
#include <QBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qbardataitem3d.sip"
#include <QBarDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qbardataproxy3d.sip"
#include <QBarDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbarseries3d.sip"
#include <QStackedBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbardataitem3d.sip"
#include <QStackedBarDataItem3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbardataproxy3d.sip"
#include <QStackedBarDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qcategoryaxis3d.sip"
#include <QCategoryAxis3D.h>
#line 26 "sip/QtStackedBars3D/qcustomitem3d.sip"
#include <QCustomItem3D.h>
#line 32 "sip/QtStackedBars3D/qcustomitem3d.sip"
#include <QCustomItem3D.h>
#line 263 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 32 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 286 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 32 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 309 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qimage.sip"
#include <qimage.h>
#line 312 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qsize.sip"
#include <qsize.h>
#line 315 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 253 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qevent.sip"
#include <qevent.h>
#line 318 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 205 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qevent.sip"
#include <qevent.h>
#line 321 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 714 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qevent.sip"
#include <qevent.h>
#line 324 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 783 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qevent.sip"
#include <qevent.h>
#line 327 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 413 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qevent.sip"
#include <qevent.h>
#line 330 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 333 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 32 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 356 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 32 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 375 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 32 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 400 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 32 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 417 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 149 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 420 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 149 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 423 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 426 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 429 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 189 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qglobal.sip"
#include <QtGlobal>
#line 432 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qregion.sip"
#include <qregion.h>
#line 435 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 293 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qevent.sip"
#include <qevent.h>
#line 438 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 351 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qevent.sip"
#include <qevent.h>
#line 441 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 459 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qevent.sip"
#include <qevent.h>
#line 444 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 448 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qevent.sip"
#include <qevent.h>
#line 447 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 372 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qevent.sip"
#include <qevent.h>
#line 450 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 400 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qevent.sip"
#include <qevent.h>
#line 453 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 27 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qstring.sip"
#include <qstring.h>
#line 456 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 28 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qobject.sip"
#include <qobject.h>
#line 459 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qscreen.sip"
#include <qscreen.h>
#line 462 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qcursor.sip"
#include <qcursor.h>
#line 465 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpoint.sip"
#include <qpoint.h>
#line 468 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qicon.sip"
#include <qicon.h>
#line 471 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qrect.sip"
#include <qrect.h>
#line 474 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qmargins.sip"
#include <qmargins.h>
#line 477 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 480 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qsurface.sip"
#include <qsurface.h>
#line 483 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 486 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 247 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 489 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 235 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 492 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qvariant.sip"
#include <qvariant.h>
#line 495 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 38 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 498 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 30 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 501 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 149 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 504 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qthread.sip"
#include <qthread.h>
#line 507 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 510 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qregexp.sip"
#include <qregexp.h>
#line 513 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 516 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 519 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQStackedBars3D.cpp"


class sipQtStackedBar3DVis_QStackedBars3D : public  ::QtStackedBar3DVis::QStackedBars3D
{
public:
    sipQtStackedBar3DVis_QStackedBars3D(const  ::QSurfaceFormat*, ::QWindow*);
    virtual ~sipQtStackedBar3DVis_QStackedBars3D();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    void tabletEvent( ::QTabletEvent*);
    void touchEvent( ::QTouchEvent*);
    void wheelEvent( ::QWheelEvent*);
    void mouseMoveEvent( ::QMouseEvent*);
    void mouseDoubleClickEvent( ::QMouseEvent*);
    void mouseReleaseEvent( ::QMouseEvent*);
    void mousePressEvent( ::QMouseEvent*);
    void keyReleaseEvent( ::QKeyEvent*);
    void keyPressEvent( ::QKeyEvent*);
    void hideEvent( ::QHideEvent*);
    void showEvent( ::QShowEvent*);
    void focusOutEvent( ::QFocusEvent*);
    void focusInEvent( ::QFocusEvent*);
    void moveEvent( ::QMoveEvent*);
    void resizeEvent( ::QResizeEvent*);
    void exposeEvent( ::QExposeEvent*);
     ::QObject* focusObject() const;
     ::QSurfaceFormat format() const;
     ::QSurface::SurfaceType surfaceType() const;
     ::QSize size() const;
    bool event( ::QEvent*);
    bool eventFilter( ::QObject*, ::QEvent*);
    void timerEvent( ::QTimerEvent*);
    void childEvent( ::QChildEvent*);
    void customEvent( ::QEvent*);
    void connectNotify(const  ::QMetaMethod&);
    void disconnectNotify(const  ::QMetaMethod&);
    bool shadowsSupported() const;

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQtStackedBar3DVis_QStackedBars3D(const sipQtStackedBar3DVis_QStackedBars3D &);
    sipQtStackedBar3DVis_QStackedBars3D &operator = (const sipQtStackedBar3DVis_QStackedBars3D &);

    char sipPyMethods[28];
};

sipQtStackedBar3DVis_QStackedBars3D::sipQtStackedBar3DVis_QStackedBars3D(const  ::QSurfaceFormat*a0, ::QWindow*a1):  ::QtStackedBar3DVis::QStackedBars3D(a0,a1), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQtStackedBar3DVis_QStackedBars3D::~sipQtStackedBar3DVis_QStackedBars3D()
{
    sipInstanceDestroyedEx(&sipPySelf);
}

const QMetaObject *sipQtStackedBar3DVis_QStackedBars3D::metaObject() const
{
    if (sipGetInterpreter())
        return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : sip_QtStackedBars3D_qt_metaobject(sipPySelf,sipType_QtStackedBar3DVis_QStackedBars3D);

    return  ::QtStackedBar3DVis::QStackedBars3D::metaObject();
}

int sipQtStackedBar3DVis_QStackedBars3D::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id =  ::QtStackedBar3DVis::QStackedBars3D::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_QtStackedBars3D_qt_metacall(sipPySelf,sipType_QtStackedBar3DVis_QStackedBars3D,_c,_id,_a);

    return _id;
}

void *sipQtStackedBar3DVis_QStackedBars3D::qt_metacast(const char *_clname)
{
    void *sipCpp;

    return (sip_QtStackedBars3D_qt_metacast(sipPySelf, sipType_QtStackedBar3DVis_QStackedBars3D, _clname, &sipCpp) ? sipCpp :  ::QtStackedBar3DVis::QStackedBars3D::qt_metacast(_clname));
}

void sipQtStackedBar3DVis_QStackedBars3D::tabletEvent( ::QTabletEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_tabletEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::tabletEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_0(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QTabletEvent*);

    sipVH_QtStackedBars3D_0(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::touchEvent( ::QTouchEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_touchEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::touchEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_1(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QTouchEvent*);

    sipVH_QtStackedBars3D_1(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::wheelEvent( ::QWheelEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_wheelEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::wheelEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_2(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QWheelEvent*);

    sipVH_QtStackedBars3D_2(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::mouseMoveEvent( ::QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_mouseMoveEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::mouseMoveEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_3(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QMouseEvent*);

    sipVH_QtStackedBars3D_3(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::mouseDoubleClickEvent( ::QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_mouseDoubleClickEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::mouseDoubleClickEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_3(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QMouseEvent*);

    sipVH_QtStackedBars3D_3(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::mouseReleaseEvent( ::QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_mouseReleaseEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::mouseReleaseEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_3(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QMouseEvent*);

    sipVH_QtStackedBars3D_3(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::mousePressEvent( ::QMouseEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_mousePressEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::mousePressEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_3(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QMouseEvent*);

    sipVH_QtStackedBars3D_3(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::keyReleaseEvent( ::QKeyEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[7],sipPySelf,NULL,sipName_keyReleaseEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::keyReleaseEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_4(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QKeyEvent*);

    sipVH_QtStackedBars3D_4(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::keyPressEvent( ::QKeyEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[8],sipPySelf,NULL,sipName_keyPressEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::keyPressEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_4(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QKeyEvent*);

    sipVH_QtStackedBars3D_4(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::hideEvent( ::QHideEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[9],sipPySelf,NULL,sipName_hideEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::hideEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_5(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QHideEvent*);

    sipVH_QtStackedBars3D_5(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::showEvent( ::QShowEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[10],sipPySelf,NULL,sipName_showEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::showEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_6(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QShowEvent*);

    sipVH_QtStackedBars3D_6(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::focusOutEvent( ::QFocusEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[11],sipPySelf,NULL,sipName_focusOutEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::focusOutEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_7(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QFocusEvent*);

    sipVH_QtStackedBars3D_7(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::focusInEvent( ::QFocusEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[12],sipPySelf,NULL,sipName_focusInEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::focusInEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_7(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QFocusEvent*);

    sipVH_QtStackedBars3D_7(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::moveEvent( ::QMoveEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[13],sipPySelf,NULL,sipName_moveEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::moveEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_8(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QMoveEvent*);

    sipVH_QtStackedBars3D_8(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::resizeEvent( ::QResizeEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[14],sipPySelf,NULL,sipName_resizeEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::resizeEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_9(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QResizeEvent*);

    sipVH_QtStackedBars3D_9(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::exposeEvent( ::QExposeEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[15],sipPySelf,NULL,sipName_exposeEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::exposeEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_10(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QExposeEvent*);

    sipVH_QtStackedBars3D_10(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

 ::QObject* sipQtStackedBar3DVis_QStackedBars3D::focusObject() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[16]),sipPySelf,NULL,sipName_focusObject);

    if (!sipMeth)
        return  ::QtStackedBar3DVis::QStackedBars3D::focusObject();

    extern  ::QObject* sipVH_QtStackedBars3D_11(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtStackedBars3D_11(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

 ::QSurfaceFormat sipQtStackedBar3DVis_QStackedBars3D::format() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[17]),sipPySelf,NULL,sipName_format);

    if (!sipMeth)
        return  ::QtStackedBar3DVis::QStackedBars3D::format();

    extern  ::QSurfaceFormat sipVH_QtStackedBars3D_12(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtStackedBars3D_12(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

 ::QSurface::SurfaceType sipQtStackedBar3DVis_QStackedBars3D::surfaceType() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[18]),sipPySelf,NULL,sipName_surfaceType);

    if (!sipMeth)
        return  ::QtStackedBar3DVis::QStackedBars3D::surfaceType();

    extern  ::QSurface::SurfaceType sipVH_QtStackedBars3D_13(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtStackedBars3D_13(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

 ::QSize sipQtStackedBar3DVis_QStackedBars3D::size() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[19]),sipPySelf,NULL,sipName_size);

    if (!sipMeth)
        return  ::QtStackedBar3DVis::QStackedBars3D::size();

    extern  ::QSize sipVH_QtStackedBars3D_14(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtStackedBars3D_14(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}

bool sipQtStackedBar3DVis_QStackedBars3D::event( ::QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[20],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return  ::QtStackedBar3DVis::QStackedBars3D::event(a0);

    extern bool sipVH_QtStackedBars3D_15(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QEvent*);

    return sipVH_QtStackedBars3D_15(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

bool sipQtStackedBar3DVis_QStackedBars3D::eventFilter( ::QObject*a0, ::QEvent*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[21],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return  ::QtStackedBar3DVis::QStackedBars3D::eventFilter(a0,a1);

    extern bool sipVH_QtStackedBars3D_16(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QObject*, ::QEvent*);

    return sipVH_QtStackedBars3D_16(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0, a1);
}

void sipQtStackedBar3DVis_QStackedBars3D::timerEvent( ::QTimerEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[22],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::timerEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_17(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QTimerEvent*);

    sipVH_QtStackedBars3D_17(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::childEvent( ::QChildEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[23],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::childEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_18(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QChildEvent*);

    sipVH_QtStackedBars3D_18(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::customEvent( ::QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[24],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::customEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_19(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QEvent*);

    sipVH_QtStackedBars3D_19(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::connectNotify(const  ::QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[25],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::connectNotify(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_20(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QMetaMethod&);

    sipVH_QtStackedBars3D_20(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QStackedBars3D::disconnectNotify(const  ::QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[26],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QStackedBars3D::disconnectNotify(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_20(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QMetaMethod&);

    sipVH_QtStackedBars3D_20(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

bool sipQtStackedBar3DVis_QStackedBars3D::shadowsSupported() const
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,const_cast<char *>(&sipPyMethods[27]),sipPySelf,NULL,sipName_shadowsSupported);

    if (!sipMeth)
        return  ::QtStackedBar3DVis::QStackedBars3D::shadowsSupported();

    extern bool sipVH_QtStackedBars3D_21(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *);

    return sipVH_QtStackedBars3D_21(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth);
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_setPrimarySeries, "setPrimarySeries(self, QtStackedBar3DVis.QStackedBarSeries3D)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setPrimarySeries(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setPrimarySeries(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QStackedBarSeries3D* a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ:", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, sipType_QtStackedBar3DVis_QStackedBarSeries3D, &a0))
        {
            sipCpp->setPrimarySeries(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_setPrimarySeries, doc_QtStackedBar3DVis_QStackedBars3D_setPrimarySeries);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_primarySeries, "primarySeries(self) -> QtStackedBar3DVis.QStackedBarSeries3D");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_primarySeries(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_primarySeries(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
             ::QtStackedBar3DVis::QStackedBarSeries3D*sipRes;

            sipRes = sipCpp->primarySeries();

            return sipConvertFromType(sipRes,sipType_QtStackedBar3DVis_QStackedBarSeries3D,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_primarySeries, doc_QtStackedBar3DVis_QStackedBars3D_primarySeries);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_addSeries, "addSeries(self, QtStackedBar3DVis.QStackedBarSeries3D)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_addSeries(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_addSeries(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QStackedBarSeries3D* a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ:", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, sipType_QtStackedBar3DVis_QStackedBarSeries3D, &a0))
        {
            sipCpp->addSeries(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_addSeries, doc_QtStackedBar3DVis_QStackedBars3D_addSeries);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_removeSeries, "removeSeries(self, QtStackedBar3DVis.QStackedBarSeries3D)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_removeSeries(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_removeSeries(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QStackedBarSeries3D* a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ<", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, sipType_QtStackedBar3DVis_QStackedBarSeries3D, &a0))
        {
            sipCpp->removeSeries(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_removeSeries, doc_QtStackedBar3DVis_QStackedBars3D_removeSeries);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_insertSeries, "insertSeries(self, int, QtStackedBar3DVis.QStackedBarSeries3D)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_insertSeries(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_insertSeries(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        int a0;
         ::QtStackedBar3DVis::QStackedBarSeries3D* a1;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BiJ:", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, &a0, sipType_QtStackedBar3DVis_QStackedBarSeries3D, &a1))
        {
            sipCpp->insertSeries(a0,a1);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_insertSeries, doc_QtStackedBar3DVis_QStackedBars3D_insertSeries);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_seriesList, "seriesList(self) -> object");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_seriesList(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_seriesList(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
            QList< ::QtStackedBar3DVis::QStackedBarSeries3D*>*sipRes;

            sipRes = new QList< ::QtStackedBar3DVis::QStackedBarSeries3D*>(sipCpp->seriesList());

            return sipConvertFromNewType(sipRes,sipType_QList_0101QtStackedBar3DVis_QStackedBarSeries3D,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_seriesList, doc_QtStackedBar3DVis_QStackedBars3D_seriesList);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_setMultiSeriesUniform, "setMultiSeriesUniform(self, bool)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setMultiSeriesUniform(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setMultiSeriesUniform(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, &a0))
        {
            sipCpp->setMultiSeriesUniform(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_setMultiSeriesUniform, doc_QtStackedBar3DVis_QStackedBars3D_setMultiSeriesUniform);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_isMultiSeriesUniform, "isMultiSeriesUniform(self) -> bool");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_isMultiSeriesUniform(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_isMultiSeriesUniform(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isMultiSeriesUniform();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_isMultiSeriesUniform, doc_QtStackedBar3DVis_QStackedBars3D_isMultiSeriesUniform);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_setBarThickness, "setBarThickness(self, float)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setBarThickness(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setBarThickness(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        float a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bf", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, &a0))
        {
            sipCpp->setBarThickness(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_setBarThickness, doc_QtStackedBar3DVis_QStackedBars3D_setBarThickness);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_barThickness, "barThickness(self) -> float");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_barThickness(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_barThickness(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
            float sipRes;

            sipRes = sipCpp->barThickness();

            return PyFloat_FromDouble((double)sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_barThickness, doc_QtStackedBar3DVis_QStackedBars3D_barThickness);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_setBarSpacing, "setBarSpacing(self, QSizeF)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setBarSpacing(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setBarSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QSizeF* a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, sipType_QSizeF, &a0))
        {
            sipCpp->setBarSpacing(*a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_setBarSpacing, doc_QtStackedBar3DVis_QStackedBars3D_setBarSpacing);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_barSpacing, "barSpacing(self) -> QSizeF");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_barSpacing(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_barSpacing(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
             ::QSizeF*sipRes;

            sipRes = new  ::QSizeF(sipCpp->barSpacing());

            return sipConvertFromNewType(sipRes,sipType_QSizeF,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_barSpacing, doc_QtStackedBar3DVis_QStackedBars3D_barSpacing);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_setBarSpacingRelative, "setBarSpacingRelative(self, bool)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setBarSpacingRelative(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setBarSpacingRelative(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, &a0))
        {
            sipCpp->setBarSpacingRelative(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_setBarSpacingRelative, doc_QtStackedBar3DVis_QStackedBars3D_setBarSpacingRelative);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_isBarSpacingRelative, "isBarSpacingRelative(self) -> bool");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_isBarSpacingRelative(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_isBarSpacingRelative(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isBarSpacingRelative();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_isBarSpacingRelative, doc_QtStackedBar3DVis_QStackedBars3D_isBarSpacingRelative);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_setRowAxis, "setRowAxis(self, QtStackedBar3DVis.QCategoryAxis3D)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setRowAxis(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setRowAxis(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QCategoryAxis3D* a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ:", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, sipType_QtStackedBar3DVis_QCategoryAxis3D, &a0))
        {
            sipCpp->setRowAxis(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_setRowAxis, doc_QtStackedBar3DVis_QStackedBars3D_setRowAxis);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_rowAxis, "rowAxis(self) -> QtStackedBar3DVis.QCategoryAxis3D");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_rowAxis(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_rowAxis(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
             ::QtStackedBar3DVis::QCategoryAxis3D*sipRes;

            sipRes = sipCpp->rowAxis();

            return sipConvertFromType(sipRes,sipType_QtStackedBar3DVis_QCategoryAxis3D,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_rowAxis, doc_QtStackedBar3DVis_QStackedBars3D_rowAxis);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_setColumnAxis, "setColumnAxis(self, QtStackedBar3DVis.QCategoryAxis3D)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setColumnAxis(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setColumnAxis(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QCategoryAxis3D* a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ:", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, sipType_QtStackedBar3DVis_QCategoryAxis3D, &a0))
        {
            sipCpp->setColumnAxis(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_setColumnAxis, doc_QtStackedBar3DVis_QStackedBars3D_setColumnAxis);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_columnAxis, "columnAxis(self) -> QtStackedBar3DVis.QCategoryAxis3D");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_columnAxis(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_columnAxis(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
             ::QtStackedBar3DVis::QCategoryAxis3D*sipRes;

            sipRes = sipCpp->columnAxis();

            return sipConvertFromType(sipRes,sipType_QtStackedBar3DVis_QCategoryAxis3D,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_columnAxis, doc_QtStackedBar3DVis_QStackedBars3D_columnAxis);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_setValueAxis, "setValueAxis(self, QtStackedBar3DVis.QValueAxis3D)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setValueAxis(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setValueAxis(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QValueAxis3D* a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ:", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, sipType_QtStackedBar3DVis_QValueAxis3D, &a0))
        {
            sipCpp->setValueAxis(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_setValueAxis, doc_QtStackedBar3DVis_QStackedBars3D_setValueAxis);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_valueAxis, "valueAxis(self) -> QtStackedBar3DVis.QValueAxis3D");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_valueAxis(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_valueAxis(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
             ::QtStackedBar3DVis::QValueAxis3D*sipRes;

            sipRes = sipCpp->valueAxis();

            return sipConvertFromType(sipRes,sipType_QtStackedBar3DVis_QValueAxis3D,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_valueAxis, doc_QtStackedBar3DVis_QStackedBars3D_valueAxis);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_addAxis, "addAxis(self, QtStackedBar3DVis.QAbstractAxis3D)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_addAxis(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_addAxis(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QAbstractAxis3D* a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ:", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, sipType_QtStackedBar3DVis_QAbstractAxis3D, &a0))
        {
            sipCpp->addAxis(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_addAxis, doc_QtStackedBar3DVis_QStackedBars3D_addAxis);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_releaseAxis, "releaseAxis(self, QtStackedBar3DVis.QAbstractAxis3D)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_releaseAxis(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_releaseAxis(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QAbstractAxis3D* a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ<", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, sipType_QtStackedBar3DVis_QAbstractAxis3D, &a0))
        {
            sipCpp->releaseAxis(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_releaseAxis, doc_QtStackedBar3DVis_QStackedBars3D_releaseAxis);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_axes, "axes(self) -> List[QtStackedBar3DVis.QAbstractAxis3D]");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_axes(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_axes(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
            QList< ::QtStackedBar3DVis::QAbstractAxis3D*>*sipRes;

            sipRes = new QList< ::QtStackedBar3DVis::QAbstractAxis3D*>(sipCpp->axes());

            return sipConvertFromNewType(sipRes,sipType_QList_0101QtStackedBar3DVis_QAbstractAxis3D,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_axes, doc_QtStackedBar3DVis_QStackedBars3D_axes);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_selectedSeries, "selectedSeries(self) -> QtStackedBar3DVis.QStackedBarSeries3D");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_selectedSeries(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_selectedSeries(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
             ::QtStackedBar3DVis::QStackedBarSeries3D*sipRes;

            sipRes = sipCpp->selectedSeries();

            return sipConvertFromType(sipRes,sipType_QtStackedBar3DVis_QStackedBarSeries3D,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_selectedSeries, doc_QtStackedBar3DVis_QStackedBars3D_selectedSeries);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_setFloorLevel, "setFloorLevel(self, float)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setFloorLevel(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_setFloorLevel(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        float a0;
         ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bf", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp, &a0))
        {
            sipCpp->setFloorLevel(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_setFloorLevel, doc_QtStackedBar3DVis_QStackedBars3D_setFloorLevel);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D_floorLevel, "floorLevel(self) -> float");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_floorLevel(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QStackedBars3D_floorLevel(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QStackedBars3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QStackedBars3D, &sipCpp))
        {
            float sipRes;

            sipRes = sipCpp->floorLevel();

            return PyFloat_FromDouble((double)sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QStackedBars3D, sipName_floorLevel, doc_QtStackedBar3DVis_QStackedBars3D_floorLevel);

    return NULL;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_QtStackedBar3DVis_QStackedBars3D(void *, const sipTypeDef *);}
static void *cast_QtStackedBar3DVis_QStackedBars3D(void *sipCppV, const sipTypeDef *targetType)
{
     ::QtStackedBar3DVis::QStackedBars3D *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QStackedBars3D *>(sipCppV);

    if (targetType == sipType_QtStackedBar3DVis_QAbstractGraph3D)
        return static_cast< ::QtStackedBar3DVis::QAbstractGraph3D *>(sipCpp);

    if (targetType == sipType_QWindow)
        return static_cast< ::QWindow *>(sipCpp);

    if (targetType == sipType_QObject)
        return static_cast< ::QObject *>(sipCpp);

    if (targetType == sipType_QSurface)
        return static_cast< ::QSurface *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_QtStackedBar3DVis_QStackedBars3D(void *, int);}
static void release_QtStackedBar3DVis_QStackedBars3D(void *sipCppV, int)
{
     ::QtStackedBar3DVis::QStackedBars3D *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QStackedBars3D *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QtStackedBar3DVis_QStackedBars3D(sipSimpleWrapper *);}
static void dealloc_QtStackedBar3DVis_QStackedBars3D(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipQtStackedBar3DVis_QStackedBars3D *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_QtStackedBar3DVis_QStackedBars3D(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_QtStackedBar3DVis_QStackedBars3D(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QtStackedBar3DVis_QStackedBars3D(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQtStackedBar3DVis_QStackedBars3D *sipCpp = 0;

    {
        const  ::QSurfaceFormat* a0 = 0;
         ::QWindow* a1 = 0;

        static const char *sipKwdList[] = {
            sipName_format,
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|J8JH", sipType_QSurfaceFormat, &a0, sipType_QWindow, &a1, sipOwner))
        {
            sipCpp = new sipQtStackedBar3DVis_QStackedBars3D(a0,a1);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QtStackedBar3DVis_QStackedBars3D[] = {{20, 255, 1}};


static PyMethodDef methods_QtStackedBar3DVis_QStackedBars3D[] = {
    {SIP_MLNAME_CAST(sipName_addAxis), meth_QtStackedBar3DVis_QStackedBars3D_addAxis, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_addAxis)},
    {SIP_MLNAME_CAST(sipName_addSeries), meth_QtStackedBar3DVis_QStackedBars3D_addSeries, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_addSeries)},
    {SIP_MLNAME_CAST(sipName_axes), meth_QtStackedBar3DVis_QStackedBars3D_axes, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_axes)},
    {SIP_MLNAME_CAST(sipName_barSpacing), meth_QtStackedBar3DVis_QStackedBars3D_barSpacing, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_barSpacing)},
    {SIP_MLNAME_CAST(sipName_barThickness), meth_QtStackedBar3DVis_QStackedBars3D_barThickness, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_barThickness)},
    {SIP_MLNAME_CAST(sipName_columnAxis), meth_QtStackedBar3DVis_QStackedBars3D_columnAxis, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_columnAxis)},
    {SIP_MLNAME_CAST(sipName_floorLevel), meth_QtStackedBar3DVis_QStackedBars3D_floorLevel, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_floorLevel)},
    {SIP_MLNAME_CAST(sipName_insertSeries), meth_QtStackedBar3DVis_QStackedBars3D_insertSeries, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_insertSeries)},
    {SIP_MLNAME_CAST(sipName_isBarSpacingRelative), meth_QtStackedBar3DVis_QStackedBars3D_isBarSpacingRelative, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_isBarSpacingRelative)},
    {SIP_MLNAME_CAST(sipName_isMultiSeriesUniform), meth_QtStackedBar3DVis_QStackedBars3D_isMultiSeriesUniform, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_isMultiSeriesUniform)},
    {SIP_MLNAME_CAST(sipName_primarySeries), meth_QtStackedBar3DVis_QStackedBars3D_primarySeries, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_primarySeries)},
    {SIP_MLNAME_CAST(sipName_releaseAxis), meth_QtStackedBar3DVis_QStackedBars3D_releaseAxis, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_releaseAxis)},
    {SIP_MLNAME_CAST(sipName_removeSeries), meth_QtStackedBar3DVis_QStackedBars3D_removeSeries, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_removeSeries)},
    {SIP_MLNAME_CAST(sipName_rowAxis), meth_QtStackedBar3DVis_QStackedBars3D_rowAxis, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_rowAxis)},
    {SIP_MLNAME_CAST(sipName_selectedSeries), meth_QtStackedBar3DVis_QStackedBars3D_selectedSeries, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_selectedSeries)},
    {SIP_MLNAME_CAST(sipName_seriesList), meth_QtStackedBar3DVis_QStackedBars3D_seriesList, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_seriesList)},
    {SIP_MLNAME_CAST(sipName_setBarSpacing), meth_QtStackedBar3DVis_QStackedBars3D_setBarSpacing, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_setBarSpacing)},
    {SIP_MLNAME_CAST(sipName_setBarSpacingRelative), meth_QtStackedBar3DVis_QStackedBars3D_setBarSpacingRelative, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_setBarSpacingRelative)},
    {SIP_MLNAME_CAST(sipName_setBarThickness), meth_QtStackedBar3DVis_QStackedBars3D_setBarThickness, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_setBarThickness)},
    {SIP_MLNAME_CAST(sipName_setColumnAxis), meth_QtStackedBar3DVis_QStackedBars3D_setColumnAxis, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_setColumnAxis)},
    {SIP_MLNAME_CAST(sipName_setFloorLevel), meth_QtStackedBar3DVis_QStackedBars3D_setFloorLevel, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_setFloorLevel)},
    {SIP_MLNAME_CAST(sipName_setMultiSeriesUniform), meth_QtStackedBar3DVis_QStackedBars3D_setMultiSeriesUniform, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_setMultiSeriesUniform)},
    {SIP_MLNAME_CAST(sipName_setPrimarySeries), meth_QtStackedBar3DVis_QStackedBars3D_setPrimarySeries, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_setPrimarySeries)},
    {SIP_MLNAME_CAST(sipName_setRowAxis), meth_QtStackedBar3DVis_QStackedBars3D_setRowAxis, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_setRowAxis)},
    {SIP_MLNAME_CAST(sipName_setValueAxis), meth_QtStackedBar3DVis_QStackedBars3D_setValueAxis, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_setValueAxis)},
    {SIP_MLNAME_CAST(sipName_valueAxis), meth_QtStackedBar3DVis_QStackedBars3D_valueAxis, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QStackedBars3D_valueAxis)}
};

PyDoc_STRVAR(doc_QtStackedBar3DVis_QStackedBars3D, "\1QtStackedBar3DVis.QStackedBars3D(format: QSurfaceFormat = None, parent: QWindow = None)");


/* Define this type's signals. */
static const pyqt5QtSignal signals_QtStackedBar3DVis_QStackedBars3D[] = {
    {"floorLevelChanged(float)", "\1floorLevelChanged(self, float)", 0, 0},
    {"selectedSeriesChanged(QStackedBarSeries3D*)|(QtStackedBar3DVis::QStackedBarSeries3D*)", "\1selectedSeriesChanged(self, QtStackedBar3DVis.QStackedBarSeries3D)", 0, 0},
    {"primarySeriesChanged(QStackedBarSeries3D*)|(QtStackedBar3DVis::QStackedBarSeries3D*)", "\1primarySeriesChanged(self, QtStackedBar3DVis.QStackedBarSeries3D)", 0, 0},
    {"valueAxisChanged(QValueAxis3D*)|(QtStackedBar3DVis::QValueAxis3D*)", "\1valueAxisChanged(self, QtStackedBar3DVis.QValueAxis3D)", 0, 0},
    {"columnAxisChanged(QCategoryAxis3D*)|(QtStackedBar3DVis::QCategoryAxis3D*)", "\1columnAxisChanged(self, QtStackedBar3DVis.QCategoryAxis3D)", 0, 0},
    {"rowAxisChanged(QCategoryAxis3D*)|(QtStackedBar3DVis::QCategoryAxis3D*)", "\1rowAxisChanged(self, QtStackedBar3DVis.QCategoryAxis3D)", 0, 0},
    {"barSpacingRelativeChanged(bool)", "\1barSpacingRelativeChanged(self, bool)", 0, 0},
    {"barSpacingChanged(QSizeF)", "\1barSpacingChanged(self, QSizeF)", 0, 0},
    {"barThicknessChanged(float)", "\1barThicknessChanged(self, float)", 0, 0},
    {"multiSeriesUniformChanged(bool)", "\1multiSeriesUniformChanged(self, bool)", 0, 0},
    {0, 0, 0, 0}
};


static pyqt5ClassPluginDef plugin_QtStackedBar3DVis_QStackedBars3D = {
    & ::QtStackedBar3DVis::QStackedBars3D::staticMetaObject,
    0,
    signals_QtStackedBar3DVis_QStackedBars3D,
    0
};


sipClassTypeDef sipTypeDef_QtStackedBars3D_QtStackedBar3DVis_QStackedBars3D = {
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QtStackedBar3DVis__QStackedBars3D,
        {0},
        &plugin_QtStackedBar3DVis_QStackedBars3D
    },
    {
        sipNameNr_QStackedBars3D,
        {14, 255, 0},
        26, methods_QtStackedBar3DVis_QStackedBars3D,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QtStackedBar3DVis_QStackedBars3D,
    -1,
    -1,
    supers_QtStackedBar3DVis_QStackedBars3D,
    0,
    init_type_QtStackedBar3DVis_QStackedBars3D,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QtStackedBar3DVis_QStackedBars3D,
    0,
    0,
    0,
    release_QtStackedBar3DVis_QStackedBars3D,
    cast_QtStackedBar3DVis_QStackedBars3D,
    0,
    0,
    0,
    0,
    0,
    0
};
