/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.12
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQtStackedBars3D.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtStackedBars3D.h"

#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 32 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 43 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"

#line 28 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qobject.sip"
#include <qobject.h>
#line 47 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qfont.sip"
#include <qfont.h>
#line 50 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 165 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qbrush.sip"
#include <qbrush.h>
#line 53 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 38 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 56 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtGui/qcolor.sip"
#include <qcolor.h>
#line 59 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 38 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 62 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qmetaobject.sip"
#include <qmetaobject.h>
#line 65 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 68 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 247 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 71 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 235 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qcoreevent.sip"
#include <qcoreevent.h>
#line 74 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 27 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qstring.sip"
#include <qstring.h>
#line 77 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qvariant.sip"
#include <qvariant.h>
#line 80 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 38 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 83 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 30 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qbytearray.sip"
#include <qbytearray.h>
#line 86 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 149 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qpycore_qlist.sip"
#include <qlist.h>
#line 89 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 92 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qthread.sip"
#include <qthread.h>
#line 95 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qnamespace.sip"
#include <qnamespace.h>
#line 98 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qregexp.sip"
#include <qregexp.h>
#line 101 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qregularexpression.sip"
#include <qregularexpression.h>
#line 104 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"
#line 26 "/trunet/data/volume2/virtualenvs/zyklio_python_packages_dbg/share/sip/PyQt5/QtCore/qobjectdefs.sip"
#include <qobjectdefs.h>
#line 107 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQTheme3D.cpp"


class sipQtStackedBar3DVis_QTheme3D : public  ::QtStackedBar3DVis::QTheme3D
{
public:
    sipQtStackedBar3DVis_QTheme3D( ::QObject*);
    sipQtStackedBar3DVis_QTheme3D( ::QtStackedBar3DVis::QTheme3D::Theme, ::QObject*);
    virtual ~sipQtStackedBar3DVis_QTheme3D();

    int qt_metacall(QMetaObject::Call,int,void **);
    void *qt_metacast(const char *);
    const QMetaObject *metaObject() const;

    /*
     * There is a protected method for every virtual method visible from
     * this class.
     */
protected:
    bool event( ::QEvent*);
    bool eventFilter( ::QObject*, ::QEvent*);
    void timerEvent( ::QTimerEvent*);
    void childEvent( ::QChildEvent*);
    void customEvent( ::QEvent*);
    void connectNotify(const  ::QMetaMethod&);
    void disconnectNotify(const  ::QMetaMethod&);

public:
    sipSimpleWrapper *sipPySelf;

private:
    sipQtStackedBar3DVis_QTheme3D(const sipQtStackedBar3DVis_QTheme3D &);
    sipQtStackedBar3DVis_QTheme3D &operator = (const sipQtStackedBar3DVis_QTheme3D &);

    char sipPyMethods[7];
};

sipQtStackedBar3DVis_QTheme3D::sipQtStackedBar3DVis_QTheme3D( ::QObject*a0):  ::QtStackedBar3DVis::QTheme3D(a0), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQtStackedBar3DVis_QTheme3D::sipQtStackedBar3DVis_QTheme3D( ::QtStackedBar3DVis::QTheme3D::Theme a0, ::QObject*a1):  ::QtStackedBar3DVis::QTheme3D(a0,a1), sipPySelf(0)
{
    memset(sipPyMethods, 0, sizeof (sipPyMethods));
}

sipQtStackedBar3DVis_QTheme3D::~sipQtStackedBar3DVis_QTheme3D()
{
    sipInstanceDestroyedEx(&sipPySelf);
}

const QMetaObject *sipQtStackedBar3DVis_QTheme3D::metaObject() const
{
    if (sipGetInterpreter())
        return QObject::d_ptr->metaObject ? QObject::d_ptr->dynamicMetaObject() : sip_QtStackedBars3D_qt_metaobject(sipPySelf,sipType_QtStackedBar3DVis_QTheme3D);

    return  ::QtStackedBar3DVis::QTheme3D::metaObject();
}

int sipQtStackedBar3DVis_QTheme3D::qt_metacall(QMetaObject::Call _c,int _id,void **_a)
{
    _id =  ::QtStackedBar3DVis::QTheme3D::qt_metacall(_c,_id,_a);

    if (_id >= 0)
        _id = sip_QtStackedBars3D_qt_metacall(sipPySelf,sipType_QtStackedBar3DVis_QTheme3D,_c,_id,_a);

    return _id;
}

void *sipQtStackedBar3DVis_QTheme3D::qt_metacast(const char *_clname)
{
    void *sipCpp;

    return (sip_QtStackedBars3D_qt_metacast(sipPySelf, sipType_QtStackedBar3DVis_QTheme3D, _clname, &sipCpp) ? sipCpp :  ::QtStackedBar3DVis::QTheme3D::qt_metacast(_clname));
}

bool sipQtStackedBar3DVis_QTheme3D::event( ::QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[0],sipPySelf,NULL,sipName_event);

    if (!sipMeth)
        return  ::QtStackedBar3DVis::QTheme3D::event(a0);

    extern bool sipVH_QtStackedBars3D_15(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QEvent*);

    return sipVH_QtStackedBars3D_15(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

bool sipQtStackedBar3DVis_QTheme3D::eventFilter( ::QObject*a0, ::QEvent*a1)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[1],sipPySelf,NULL,sipName_eventFilter);

    if (!sipMeth)
        return  ::QtStackedBar3DVis::QTheme3D::eventFilter(a0,a1);

    extern bool sipVH_QtStackedBars3D_16(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QObject*, ::QEvent*);

    return sipVH_QtStackedBars3D_16(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0, a1);
}

void sipQtStackedBar3DVis_QTheme3D::timerEvent( ::QTimerEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[2],sipPySelf,NULL,sipName_timerEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QTheme3D::timerEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_17(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QTimerEvent*);

    sipVH_QtStackedBars3D_17(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QTheme3D::childEvent( ::QChildEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[3],sipPySelf,NULL,sipName_childEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QTheme3D::childEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_18(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QChildEvent*);

    sipVH_QtStackedBars3D_18(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QTheme3D::customEvent( ::QEvent*a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[4],sipPySelf,NULL,sipName_customEvent);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QTheme3D::customEvent(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_19(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *,  ::QEvent*);

    sipVH_QtStackedBars3D_19(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QTheme3D::connectNotify(const  ::QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[5],sipPySelf,NULL,sipName_connectNotify);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QTheme3D::connectNotify(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_20(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QMetaMethod&);

    sipVH_QtStackedBars3D_20(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}

void sipQtStackedBar3DVis_QTheme3D::disconnectNotify(const  ::QMetaMethod& a0)
{
    sip_gilstate_t sipGILState;
    PyObject *sipMeth;

    sipMeth = sipIsPyMethod(&sipGILState,&sipPyMethods[6],sipPySelf,NULL,sipName_disconnectNotify);

    if (!sipMeth)
    {
         ::QtStackedBar3DVis::QTheme3D::disconnectNotify(a0);
        return;
    }

    extern void sipVH_QtStackedBars3D_20(sip_gilstate_t, sipVirtErrorHandlerFunc, sipSimpleWrapper *, PyObject *, const  ::QMetaMethod&);

    sipVH_QtStackedBars3D_20(sipGILState, sipImportedVirtErrorHandlers_QtStackedBars3D_QtCore[0].iveh_handler, sipPySelf, sipMeth, a0);
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setType, "setType(self, QtStackedBar3DVis.QTheme3D.Theme)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setType(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setType(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QTheme3D::Theme a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QtStackedBar3DVis_QTheme3D_Theme, &a0))
        {
            sipCpp->setType(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setType, doc_QtStackedBar3DVis_QTheme3D_setType);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_type, "type(self) -> QtStackedBar3DVis.QTheme3D.Theme");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_type(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_type(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QtStackedBar3DVis::QTheme3D::Theme sipRes;

            sipRes = sipCpp->type();

            return sipConvertFromEnum(static_cast<int>(sipRes), sipType_QtStackedBar3DVis_QTheme3D_Theme);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_type, doc_QtStackedBar3DVis_QTheme3D_type);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setBaseColors, "setBaseColors(self, object)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setBaseColors(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setBaseColors(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QList< ::QColor>* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QList_0100QColor,&a0, &a0State))
        {
            sipCpp->setBaseColors(*a0);
            sipReleaseType(const_cast<QList< ::QColor> *>(a0),sipType_QList_0100QColor,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setBaseColors, doc_QtStackedBar3DVis_QTheme3D_setBaseColors);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_baseColors, "baseColors(self) -> List[QColor]");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_baseColors(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_baseColors(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
            QList< ::QColor>*sipRes;

            sipRes = new QList< ::QColor>(sipCpp->baseColors());

            return sipConvertFromNewType(sipRes,sipType_QList_0100QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_baseColors, doc_QtStackedBar3DVis_QTheme3D_baseColors);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setBackgroundColor, "setBackgroundColor(self, Union[QColor, Qt.GlobalColor])");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setBackgroundColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setBackgroundColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QColor* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QColor, &a0, &a0State))
        {
            sipCpp->setBackgroundColor(*a0);
            sipReleaseType(const_cast< ::QColor *>(a0),sipType_QColor,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setBackgroundColor, doc_QtStackedBar3DVis_QTheme3D_setBackgroundColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_backgroundColor, "backgroundColor(self) -> QColor");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_backgroundColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_backgroundColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QColor*sipRes;

            sipRes = new  ::QColor(sipCpp->backgroundColor());

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_backgroundColor, doc_QtStackedBar3DVis_QTheme3D_backgroundColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setWindowColor, "setWindowColor(self, Union[QColor, Qt.GlobalColor])");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setWindowColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setWindowColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QColor* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QColor, &a0, &a0State))
        {
            sipCpp->setWindowColor(*a0);
            sipReleaseType(const_cast< ::QColor *>(a0),sipType_QColor,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setWindowColor, doc_QtStackedBar3DVis_QTheme3D_setWindowColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_windowColor, "windowColor(self) -> QColor");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_windowColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_windowColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QColor*sipRes;

            sipRes = new  ::QColor(sipCpp->windowColor());

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_windowColor, doc_QtStackedBar3DVis_QTheme3D_windowColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setLabelTextColor, "setLabelTextColor(self, Union[QColor, Qt.GlobalColor])");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLabelTextColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLabelTextColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QColor* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QColor, &a0, &a0State))
        {
            sipCpp->setLabelTextColor(*a0);
            sipReleaseType(const_cast< ::QColor *>(a0),sipType_QColor,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setLabelTextColor, doc_QtStackedBar3DVis_QTheme3D_setLabelTextColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_labelTextColor, "labelTextColor(self) -> QColor");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_labelTextColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_labelTextColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QColor*sipRes;

            sipRes = new  ::QColor(sipCpp->labelTextColor());

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_labelTextColor, doc_QtStackedBar3DVis_QTheme3D_labelTextColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setLabelBackgroundColor, "setLabelBackgroundColor(self, Union[QColor, Qt.GlobalColor])");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLabelBackgroundColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLabelBackgroundColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QColor* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QColor, &a0, &a0State))
        {
            sipCpp->setLabelBackgroundColor(*a0);
            sipReleaseType(const_cast< ::QColor *>(a0),sipType_QColor,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setLabelBackgroundColor, doc_QtStackedBar3DVis_QTheme3D_setLabelBackgroundColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_labelBackgroundColor, "labelBackgroundColor(self) -> QColor");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_labelBackgroundColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_labelBackgroundColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QColor*sipRes;

            sipRes = new  ::QColor(sipCpp->labelBackgroundColor());

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_labelBackgroundColor, doc_QtStackedBar3DVis_QTheme3D_labelBackgroundColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setGridLineColor, "setGridLineColor(self, Union[QColor, Qt.GlobalColor])");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setGridLineColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setGridLineColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QColor* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QColor, &a0, &a0State))
        {
            sipCpp->setGridLineColor(*a0);
            sipReleaseType(const_cast< ::QColor *>(a0),sipType_QColor,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setGridLineColor, doc_QtStackedBar3DVis_QTheme3D_setGridLineColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_gridLineColor, "gridLineColor(self) -> QColor");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_gridLineColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_gridLineColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QColor*sipRes;

            sipRes = new  ::QColor(sipCpp->gridLineColor());

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_gridLineColor, doc_QtStackedBar3DVis_QTheme3D_gridLineColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setSingleHighlightColor, "setSingleHighlightColor(self, Union[QColor, Qt.GlobalColor])");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setSingleHighlightColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setSingleHighlightColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QColor* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QColor, &a0, &a0State))
        {
            sipCpp->setSingleHighlightColor(*a0);
            sipReleaseType(const_cast< ::QColor *>(a0),sipType_QColor,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setSingleHighlightColor, doc_QtStackedBar3DVis_QTheme3D_setSingleHighlightColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_singleHighlightColor, "singleHighlightColor(self) -> QColor");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_singleHighlightColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_singleHighlightColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QColor*sipRes;

            sipRes = new  ::QColor(sipCpp->singleHighlightColor());

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_singleHighlightColor, doc_QtStackedBar3DVis_QTheme3D_singleHighlightColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setMultiHighlightColor, "setMultiHighlightColor(self, Union[QColor, Qt.GlobalColor])");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setMultiHighlightColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setMultiHighlightColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QColor* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QColor, &a0, &a0State))
        {
            sipCpp->setMultiHighlightColor(*a0);
            sipReleaseType(const_cast< ::QColor *>(a0),sipType_QColor,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setMultiHighlightColor, doc_QtStackedBar3DVis_QTheme3D_setMultiHighlightColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_multiHighlightColor, "multiHighlightColor(self) -> QColor");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_multiHighlightColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_multiHighlightColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QColor*sipRes;

            sipRes = new  ::QColor(sipCpp->multiHighlightColor());

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_multiHighlightColor, doc_QtStackedBar3DVis_QTheme3D_multiHighlightColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setLightColor, "setLightColor(self, Union[QColor, Qt.GlobalColor])");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLightColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLightColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QColor* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QColor, &a0, &a0State))
        {
            sipCpp->setLightColor(*a0);
            sipReleaseType(const_cast< ::QColor *>(a0),sipType_QColor,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setLightColor, doc_QtStackedBar3DVis_QTheme3D_setLightColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_lightColor, "lightColor(self) -> QColor");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_lightColor(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_lightColor(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QColor*sipRes;

            sipRes = new  ::QColor(sipCpp->lightColor());

            return sipConvertFromNewType(sipRes,sipType_QColor,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_lightColor, doc_QtStackedBar3DVis_QTheme3D_lightColor);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setBaseGradients, "setBaseGradients(self, object)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setBaseGradients(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setBaseGradients(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const QList< ::QLinearGradient>* a0;
        int a0State = 0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ1", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QList_0100QLinearGradient,&a0, &a0State))
        {
            sipCpp->setBaseGradients(*a0);
            sipReleaseType(const_cast<QList< ::QLinearGradient> *>(a0),sipType_QList_0100QLinearGradient,a0State);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setBaseGradients, doc_QtStackedBar3DVis_QTheme3D_setBaseGradients);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_baseGradients, "baseGradients(self) -> List[QLinearGradient]");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_baseGradients(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_baseGradients(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
            QList< ::QLinearGradient>*sipRes;

            sipRes = new QList< ::QLinearGradient>(sipCpp->baseGradients());

            return sipConvertFromNewType(sipRes,sipType_QList_0100QLinearGradient,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_baseGradients, doc_QtStackedBar3DVis_QTheme3D_baseGradients);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setSingleHighlightGradient, "setSingleHighlightGradient(self, QLinearGradient)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setSingleHighlightGradient(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setSingleHighlightGradient(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QLinearGradient* a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QLinearGradient, &a0))
        {
            sipCpp->setSingleHighlightGradient(*a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setSingleHighlightGradient, doc_QtStackedBar3DVis_QTheme3D_setSingleHighlightGradient);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_singleHighlightGradient, "singleHighlightGradient(self) -> QLinearGradient");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_singleHighlightGradient(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_singleHighlightGradient(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QLinearGradient*sipRes;

            sipRes = new  ::QLinearGradient(sipCpp->singleHighlightGradient());

            return sipConvertFromNewType(sipRes,sipType_QLinearGradient,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_singleHighlightGradient, doc_QtStackedBar3DVis_QTheme3D_singleHighlightGradient);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setMultiHighlightGradient, "setMultiHighlightGradient(self, QLinearGradient)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setMultiHighlightGradient(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setMultiHighlightGradient(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QLinearGradient* a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QLinearGradient, &a0))
        {
            sipCpp->setMultiHighlightGradient(*a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setMultiHighlightGradient, doc_QtStackedBar3DVis_QTheme3D_setMultiHighlightGradient);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_multiHighlightGradient, "multiHighlightGradient(self) -> QLinearGradient");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_multiHighlightGradient(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_multiHighlightGradient(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QLinearGradient*sipRes;

            sipRes = new  ::QLinearGradient(sipCpp->multiHighlightGradient());

            return sipConvertFromNewType(sipRes,sipType_QLinearGradient,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_multiHighlightGradient, doc_QtStackedBar3DVis_QTheme3D_multiHighlightGradient);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setLightStrength, "setLightStrength(self, float)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLightStrength(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLightStrength(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        float a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bf", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, &a0))
        {
            sipCpp->setLightStrength(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setLightStrength, doc_QtStackedBar3DVis_QTheme3D_setLightStrength);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_lightStrength, "lightStrength(self) -> float");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_lightStrength(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_lightStrength(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
            float sipRes;

            sipRes = sipCpp->lightStrength();

            return PyFloat_FromDouble((double)sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_lightStrength, doc_QtStackedBar3DVis_QTheme3D_lightStrength);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setAmbientLightStrength, "setAmbientLightStrength(self, float)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setAmbientLightStrength(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setAmbientLightStrength(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        float a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bf", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, &a0))
        {
            sipCpp->setAmbientLightStrength(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setAmbientLightStrength, doc_QtStackedBar3DVis_QTheme3D_setAmbientLightStrength);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_ambientLightStrength, "ambientLightStrength(self) -> float");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_ambientLightStrength(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_ambientLightStrength(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
            float sipRes;

            sipRes = sipCpp->ambientLightStrength();

            return PyFloat_FromDouble((double)sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_ambientLightStrength, doc_QtStackedBar3DVis_QTheme3D_ambientLightStrength);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setHighlightLightStrength, "setHighlightLightStrength(self, float)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setHighlightLightStrength(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setHighlightLightStrength(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        float a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bf", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, &a0))
        {
            sipCpp->setHighlightLightStrength(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setHighlightLightStrength, doc_QtStackedBar3DVis_QTheme3D_setHighlightLightStrength);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_highlightLightStrength, "highlightLightStrength(self) -> float");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_highlightLightStrength(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_highlightLightStrength(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
            float sipRes;

            sipRes = sipCpp->highlightLightStrength();

            return PyFloat_FromDouble((double)sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_highlightLightStrength, doc_QtStackedBar3DVis_QTheme3D_highlightLightStrength);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setLabelBorderEnabled, "setLabelBorderEnabled(self, bool)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLabelBorderEnabled(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLabelBorderEnabled(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, &a0))
        {
            sipCpp->setLabelBorderEnabled(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setLabelBorderEnabled, doc_QtStackedBar3DVis_QTheme3D_setLabelBorderEnabled);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_isLabelBorderEnabled, "isLabelBorderEnabled(self) -> bool");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_isLabelBorderEnabled(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_isLabelBorderEnabled(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isLabelBorderEnabled();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_isLabelBorderEnabled, doc_QtStackedBar3DVis_QTheme3D_isLabelBorderEnabled);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setFont, "setFont(self, QFont)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setFont(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setFont(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QFont* a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BJ9", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QFont, &a0))
        {
            sipCpp->setFont(*a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setFont, doc_QtStackedBar3DVis_QTheme3D_setFont);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_font, "font(self) -> QFont");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_font(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_font(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QFont*sipRes;

            sipRes = new  ::QFont(sipCpp->font());

            return sipConvertFromNewType(sipRes,sipType_QFont,NULL);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_font, doc_QtStackedBar3DVis_QTheme3D_font);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setBackgroundEnabled, "setBackgroundEnabled(self, bool)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setBackgroundEnabled(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setBackgroundEnabled(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, &a0))
        {
            sipCpp->setBackgroundEnabled(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setBackgroundEnabled, doc_QtStackedBar3DVis_QTheme3D_setBackgroundEnabled);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_isBackgroundEnabled, "isBackgroundEnabled(self) -> bool");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_isBackgroundEnabled(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_isBackgroundEnabled(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isBackgroundEnabled();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_isBackgroundEnabled, doc_QtStackedBar3DVis_QTheme3D_isBackgroundEnabled);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setGridEnabled, "setGridEnabled(self, bool)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setGridEnabled(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setGridEnabled(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, &a0))
        {
            sipCpp->setGridEnabled(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setGridEnabled, doc_QtStackedBar3DVis_QTheme3D_setGridEnabled);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_isGridEnabled, "isGridEnabled(self) -> bool");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_isGridEnabled(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_isGridEnabled(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isGridEnabled();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_isGridEnabled, doc_QtStackedBar3DVis_QTheme3D_isGridEnabled);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setLabelBackgroundEnabled, "setLabelBackgroundEnabled(self, bool)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLabelBackgroundEnabled(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setLabelBackgroundEnabled(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        bool a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bb", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, &a0))
        {
            sipCpp->setLabelBackgroundEnabled(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setLabelBackgroundEnabled, doc_QtStackedBar3DVis_QTheme3D_setLabelBackgroundEnabled);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_isLabelBackgroundEnabled, "isLabelBackgroundEnabled(self) -> bool");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_isLabelBackgroundEnabled(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_isLabelBackgroundEnabled(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
            bool sipRes;

            sipRes = sipCpp->isLabelBackgroundEnabled();

            return PyBool_FromLong(sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_isLabelBackgroundEnabled, doc_QtStackedBar3DVis_QTheme3D_isLabelBackgroundEnabled);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_setColorStyle, "setColorStyle(self, QtStackedBar3DVis.QTheme3D.ColorStyle)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_setColorStyle(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_setColorStyle(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
         ::QtStackedBar3DVis::QTheme3D::ColorStyle a0;
         ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "BE", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp, sipType_QtStackedBar3DVis_QTheme3D_ColorStyle, &a0))
        {
            sipCpp->setColorStyle(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_setColorStyle, doc_QtStackedBar3DVis_QTheme3D_setColorStyle);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D_colorStyle, "colorStyle(self) -> QtStackedBar3DVis.QTheme3D.ColorStyle");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QTheme3D_colorStyle(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QTheme3D_colorStyle(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QTheme3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QTheme3D, &sipCpp))
        {
             ::QtStackedBar3DVis::QTheme3D::ColorStyle sipRes;

            sipRes = sipCpp->colorStyle();

            return sipConvertFromEnum(static_cast<int>(sipRes), sipType_QtStackedBar3DVis_QTheme3D_ColorStyle);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QTheme3D, sipName_colorStyle, doc_QtStackedBar3DVis_QTheme3D_colorStyle);

    return NULL;
}


/* Cast a pointer to a type somewhere in its inheritance hierarchy. */
extern "C" {static void *cast_QtStackedBar3DVis_QTheme3D(void *, const sipTypeDef *);}
static void *cast_QtStackedBar3DVis_QTheme3D(void *sipCppV, const sipTypeDef *targetType)
{
     ::QtStackedBar3DVis::QTheme3D *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QTheme3D *>(sipCppV);

    if (targetType == sipType_QObject)
        return static_cast< ::QObject *>(sipCpp);

    return sipCppV;
}


/* Call the instance's destructor. */
extern "C" {static void release_QtStackedBar3DVis_QTheme3D(void *, int);}
static void release_QtStackedBar3DVis_QTheme3D(void *sipCppV, int)
{
     ::QtStackedBar3DVis::QTheme3D *sipCpp = reinterpret_cast< ::QtStackedBar3DVis::QTheme3D *>(sipCppV);

    if (QThread::currentThread() == sipCpp->thread())
        delete sipCpp;
    else
        sipCpp->deleteLater();
}


extern "C" {static void dealloc_QtStackedBar3DVis_QTheme3D(sipSimpleWrapper *);}
static void dealloc_QtStackedBar3DVis_QTheme3D(sipSimpleWrapper *sipSelf)
{
    if (sipIsDerivedClass(sipSelf))
        reinterpret_cast<sipQtStackedBar3DVis_QTheme3D *>(sipGetAddress(sipSelf))->sipPySelf = NULL;

    if (sipIsOwnedByPython(sipSelf))
    {
        release_QtStackedBar3DVis_QTheme3D(sipGetAddress(sipSelf), sipIsDerivedClass(sipSelf));
    }
}


extern "C" {static void *init_type_QtStackedBar3DVis_QTheme3D(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QtStackedBar3DVis_QTheme3D(sipSimpleWrapper *sipSelf, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **sipOwner, PyObject **sipParseErr)
{
    sipQtStackedBar3DVis_QTheme3D *sipCpp = 0;

    {
         ::QObject* a0 = 0;

        static const char *sipKwdList[] = {
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "|JH", sipType_QObject, &a0, sipOwner))
        {
            sipCpp = new sipQtStackedBar3DVis_QTheme3D(a0);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    {
         ::QtStackedBar3DVis::QTheme3D::Theme a0;
         ::QObject* a1 = 0;

        static const char *sipKwdList[] = {
            NULL,
            sipName_parent,
        };

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, sipKwdList, sipUnused, "E|JH", sipType_QtStackedBar3DVis_QTheme3D_Theme, &a0, sipType_QObject, &a1, sipOwner))
        {
            sipCpp = new sipQtStackedBar3DVis_QTheme3D(a0,a1);

            sipCpp->sipPySelf = sipSelf;

            return sipCpp;
        }
    }

    return NULL;
}


/* Define this type's super-types. */
static sipEncodedTypeDef supers_QtStackedBar3DVis_QTheme3D[] = {{4, 0, 1}};


static PyMethodDef methods_QtStackedBar3DVis_QTheme3D[] = {
    {SIP_MLNAME_CAST(sipName_ambientLightStrength), meth_QtStackedBar3DVis_QTheme3D_ambientLightStrength, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_ambientLightStrength)},
    {SIP_MLNAME_CAST(sipName_backgroundColor), meth_QtStackedBar3DVis_QTheme3D_backgroundColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_backgroundColor)},
    {SIP_MLNAME_CAST(sipName_baseColors), meth_QtStackedBar3DVis_QTheme3D_baseColors, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_baseColors)},
    {SIP_MLNAME_CAST(sipName_baseGradients), meth_QtStackedBar3DVis_QTheme3D_baseGradients, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_baseGradients)},
    {SIP_MLNAME_CAST(sipName_colorStyle), meth_QtStackedBar3DVis_QTheme3D_colorStyle, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_colorStyle)},
    {SIP_MLNAME_CAST(sipName_font), meth_QtStackedBar3DVis_QTheme3D_font, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_font)},
    {SIP_MLNAME_CAST(sipName_gridLineColor), meth_QtStackedBar3DVis_QTheme3D_gridLineColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_gridLineColor)},
    {SIP_MLNAME_CAST(sipName_highlightLightStrength), meth_QtStackedBar3DVis_QTheme3D_highlightLightStrength, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_highlightLightStrength)},
    {SIP_MLNAME_CAST(sipName_isBackgroundEnabled), meth_QtStackedBar3DVis_QTheme3D_isBackgroundEnabled, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_isBackgroundEnabled)},
    {SIP_MLNAME_CAST(sipName_isGridEnabled), meth_QtStackedBar3DVis_QTheme3D_isGridEnabled, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_isGridEnabled)},
    {SIP_MLNAME_CAST(sipName_isLabelBackgroundEnabled), meth_QtStackedBar3DVis_QTheme3D_isLabelBackgroundEnabled, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_isLabelBackgroundEnabled)},
    {SIP_MLNAME_CAST(sipName_isLabelBorderEnabled), meth_QtStackedBar3DVis_QTheme3D_isLabelBorderEnabled, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_isLabelBorderEnabled)},
    {SIP_MLNAME_CAST(sipName_labelBackgroundColor), meth_QtStackedBar3DVis_QTheme3D_labelBackgroundColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_labelBackgroundColor)},
    {SIP_MLNAME_CAST(sipName_labelTextColor), meth_QtStackedBar3DVis_QTheme3D_labelTextColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_labelTextColor)},
    {SIP_MLNAME_CAST(sipName_lightColor), meth_QtStackedBar3DVis_QTheme3D_lightColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_lightColor)},
    {SIP_MLNAME_CAST(sipName_lightStrength), meth_QtStackedBar3DVis_QTheme3D_lightStrength, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_lightStrength)},
    {SIP_MLNAME_CAST(sipName_multiHighlightColor), meth_QtStackedBar3DVis_QTheme3D_multiHighlightColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_multiHighlightColor)},
    {SIP_MLNAME_CAST(sipName_multiHighlightGradient), meth_QtStackedBar3DVis_QTheme3D_multiHighlightGradient, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_multiHighlightGradient)},
    {SIP_MLNAME_CAST(sipName_setAmbientLightStrength), meth_QtStackedBar3DVis_QTheme3D_setAmbientLightStrength, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setAmbientLightStrength)},
    {SIP_MLNAME_CAST(sipName_setBackgroundColor), meth_QtStackedBar3DVis_QTheme3D_setBackgroundColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setBackgroundColor)},
    {SIP_MLNAME_CAST(sipName_setBackgroundEnabled), meth_QtStackedBar3DVis_QTheme3D_setBackgroundEnabled, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setBackgroundEnabled)},
    {SIP_MLNAME_CAST(sipName_setBaseColors), meth_QtStackedBar3DVis_QTheme3D_setBaseColors, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setBaseColors)},
    {SIP_MLNAME_CAST(sipName_setBaseGradients), meth_QtStackedBar3DVis_QTheme3D_setBaseGradients, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setBaseGradients)},
    {SIP_MLNAME_CAST(sipName_setColorStyle), meth_QtStackedBar3DVis_QTheme3D_setColorStyle, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setColorStyle)},
    {SIP_MLNAME_CAST(sipName_setFont), meth_QtStackedBar3DVis_QTheme3D_setFont, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setFont)},
    {SIP_MLNAME_CAST(sipName_setGridEnabled), meth_QtStackedBar3DVis_QTheme3D_setGridEnabled, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setGridEnabled)},
    {SIP_MLNAME_CAST(sipName_setGridLineColor), meth_QtStackedBar3DVis_QTheme3D_setGridLineColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setGridLineColor)},
    {SIP_MLNAME_CAST(sipName_setHighlightLightStrength), meth_QtStackedBar3DVis_QTheme3D_setHighlightLightStrength, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setHighlightLightStrength)},
    {SIP_MLNAME_CAST(sipName_setLabelBackgroundColor), meth_QtStackedBar3DVis_QTheme3D_setLabelBackgroundColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setLabelBackgroundColor)},
    {SIP_MLNAME_CAST(sipName_setLabelBackgroundEnabled), meth_QtStackedBar3DVis_QTheme3D_setLabelBackgroundEnabled, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setLabelBackgroundEnabled)},
    {SIP_MLNAME_CAST(sipName_setLabelBorderEnabled), meth_QtStackedBar3DVis_QTheme3D_setLabelBorderEnabled, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setLabelBorderEnabled)},
    {SIP_MLNAME_CAST(sipName_setLabelTextColor), meth_QtStackedBar3DVis_QTheme3D_setLabelTextColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setLabelTextColor)},
    {SIP_MLNAME_CAST(sipName_setLightColor), meth_QtStackedBar3DVis_QTheme3D_setLightColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setLightColor)},
    {SIP_MLNAME_CAST(sipName_setLightStrength), meth_QtStackedBar3DVis_QTheme3D_setLightStrength, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setLightStrength)},
    {SIP_MLNAME_CAST(sipName_setMultiHighlightColor), meth_QtStackedBar3DVis_QTheme3D_setMultiHighlightColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setMultiHighlightColor)},
    {SIP_MLNAME_CAST(sipName_setMultiHighlightGradient), meth_QtStackedBar3DVis_QTheme3D_setMultiHighlightGradient, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setMultiHighlightGradient)},
    {SIP_MLNAME_CAST(sipName_setSingleHighlightColor), meth_QtStackedBar3DVis_QTheme3D_setSingleHighlightColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setSingleHighlightColor)},
    {SIP_MLNAME_CAST(sipName_setSingleHighlightGradient), meth_QtStackedBar3DVis_QTheme3D_setSingleHighlightGradient, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setSingleHighlightGradient)},
    {SIP_MLNAME_CAST(sipName_setType), meth_QtStackedBar3DVis_QTheme3D_setType, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setType)},
    {SIP_MLNAME_CAST(sipName_setWindowColor), meth_QtStackedBar3DVis_QTheme3D_setWindowColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_setWindowColor)},
    {SIP_MLNAME_CAST(sipName_singleHighlightColor), meth_QtStackedBar3DVis_QTheme3D_singleHighlightColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_singleHighlightColor)},
    {SIP_MLNAME_CAST(sipName_singleHighlightGradient), meth_QtStackedBar3DVis_QTheme3D_singleHighlightGradient, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_singleHighlightGradient)},
    {SIP_MLNAME_CAST(sipName_type), meth_QtStackedBar3DVis_QTheme3D_type, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_type)},
    {SIP_MLNAME_CAST(sipName_windowColor), meth_QtStackedBar3DVis_QTheme3D_windowColor, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QTheme3D_windowColor)}
};

static sipEnumMemberDef enummembers_QtStackedBar3DVis_QTheme3D[] = {
    {sipName_ColorStyleObjectGradient, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ColorStyleObjectGradient), 49},
    {sipName_ColorStyleRangeGradient, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ColorStyleRangeGradient), 49},
    {sipName_ColorStyleUniform, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ColorStyleUniform), 49},
    {sipName_ThemeArmyBlue, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ThemeArmyBlue), 50},
    {sipName_ThemeDigia, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ThemeDigia), 50},
    {sipName_ThemeEbony, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ThemeEbony), 50},
    {sipName_ThemeIsabelle, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ThemeIsabelle), 50},
    {sipName_ThemePrimaryColors, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ThemePrimaryColors), 50},
    {sipName_ThemeQt, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ThemeQt), 50},
    {sipName_ThemeRetro, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ThemeRetro), 50},
    {sipName_ThemeStoneMoss, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ThemeStoneMoss), 50},
    {sipName_ThemeUserDefined, static_cast<int>( ::QtStackedBar3DVis::QTheme3D::ThemeUserDefined), 50},
};

PyDoc_STRVAR(doc_QtStackedBar3DVis_QTheme3D, "\1QtStackedBar3DVis.QTheme3D(parent: QObject = None)\n"
"QtStackedBar3DVis.QTheme3D(QtStackedBar3DVis.QTheme3D.Theme, parent: QObject = None)");


/* Define this type's signals. */
static const pyqt5QtSignal signals_QtStackedBar3DVis_QTheme3D[] = {
    {"colorStyleChanged(QTheme3D::ColorStyle)|(QtStackedBar3DVis::QTheme3D::ColorStyle)", "\1colorStyleChanged(self, QtStackedBar3DVis.QTheme3D.ColorStyle)", 0, 0},
    {"labelBackgroundEnabledChanged(bool)", "\1labelBackgroundEnabledChanged(self, bool)", 0, 0},
    {"gridEnabledChanged(bool)", "\1gridEnabledChanged(self, bool)", 0, 0},
    {"backgroundEnabledChanged(bool)", "\1backgroundEnabledChanged(self, bool)", 0, 0},
    {"fontChanged(QFont)", "\1fontChanged(self, QFont)", 0, 0},
    {"labelBorderEnabledChanged(bool)", "\1labelBorderEnabledChanged(self, bool)", 0, 0},
    {"highlightLightStrengthChanged(float)", "\1highlightLightStrengthChanged(self, float)", 0, 0},
    {"ambientLightStrengthChanged(float)", "\1ambientLightStrengthChanged(self, float)", 0, 0},
    {"lightStrengthChanged(float)", "\1lightStrengthChanged(self, float)", 0, 0},
    {"multiHighlightGradientChanged(QLinearGradient)", "\1multiHighlightGradientChanged(self, QLinearGradient)", 0, 0},
    {"singleHighlightGradientChanged(QLinearGradient)", "\1singleHighlightGradientChanged(self, QLinearGradient)", 0, 0},
    {"baseGradientsChanged(QList<QLinearGradient>)", "\1baseGradientsChanged(self, Iterable[QLinearGradient])", 0, 0},
    {"lightColorChanged(QColor)", "\1lightColorChanged(self, Union[QColor, Qt.GlobalColor])", 0, 0},
    {"multiHighlightColorChanged(QColor)", "\1multiHighlightColorChanged(self, Union[QColor, Qt.GlobalColor])", 0, 0},
    {"singleHighlightColorChanged(QColor)", "\1singleHighlightColorChanged(self, Union[QColor, Qt.GlobalColor])", 0, 0},
    {"gridLineColorChanged(QColor)", "\1gridLineColorChanged(self, Union[QColor, Qt.GlobalColor])", 0, 0},
    {"labelBackgroundColorChanged(QColor)", "\1labelBackgroundColorChanged(self, Union[QColor, Qt.GlobalColor])", 0, 0},
    {"labelTextColorChanged(QColor)", "\1labelTextColorChanged(self, Union[QColor, Qt.GlobalColor])", 0, 0},
    {"windowColorChanged(QColor)", "\1windowColorChanged(self, Union[QColor, Qt.GlobalColor])", 0, 0},
    {"backgroundColorChanged(QColor)", "\1backgroundColorChanged(self, Union[QColor, Qt.GlobalColor])", 0, 0},
    {"baseColorsChanged(QList<QColor>)", "\1baseColorsChanged(self, Iterable[Union[QColor, Qt.GlobalColor]])", 0, 0},
    {"typeChanged(QTheme3D::Theme)|(QtStackedBar3DVis::QTheme3D::Theme)", "\1typeChanged(self, QtStackedBar3DVis.QTheme3D.Theme)", 0, 0},
    {0, 0, 0, 0}
};


static pyqt5ClassPluginDef plugin_QtStackedBar3DVis_QTheme3D = {
    & ::QtStackedBar3DVis::QTheme3D::staticMetaObject,
    0,
    signals_QtStackedBar3DVis_QTheme3D,
    0
};


sipClassTypeDef sipTypeDef_QtStackedBars3D_QtStackedBar3DVis_QTheme3D = {
    {
        -1,
        0,
        0,
        SIP_TYPE_SCC|SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QtStackedBar3DVis__QTheme3D,
        {0},
        &plugin_QtStackedBar3DVis_QTheme3D
    },
    {
        sipNameNr_QTheme3D,
        {11, 255, 0},
        44, methods_QtStackedBar3DVis_QTheme3D,
        12, enummembers_QtStackedBar3DVis_QTheme3D,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QtStackedBar3DVis_QTheme3D,
    -1,
    -1,
    supers_QtStackedBar3DVis_QTheme3D,
    0,
    init_type_QtStackedBar3DVis_QTheme3D,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QtStackedBar3DVis_QTheme3D,
    0,
    0,
    0,
    release_QtStackedBar3DVis_QTheme3D,
    cast_QtStackedBar3DVis_QTheme3D,
    0,
    0,
    0,
    0,
    0,
    0
};
