/*
 * Interface wrapper code.
 *
 * Generated by SIP 4.19.12
 *
 * Copyright (c) 2018 Riverbank Computing Limited <info@riverbankcomputing.com>
 * 
 * This file is part of PyQtStackedBars3D.
 * 
 * This file may be used under the terms of the GNU General Public License
 * version 3.0 as published by the Free Software Foundation and appearing in
 * the file LICENSE included in the packaging of this file.  Please review the
 * following information to ensure the GNU General Public License version 3.0
 * requirements will be met: http://www.gnu.org/copyleft/gpl.html.
 * 
 * If you do not wish to use this file under the terms of the GPL version 3.0
 * then you may purchase a commercial license.  For more information contact
 * info@riverbankcomputing.com.
 * 
 * This file is provided AS IS with NO WARRANTY OF ANY KIND, INCLUDING THE
 * WARRANTY OF DESIGN, MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
 */

#include "sipAPIQtStackedBars3D.h"

#line 26 "sip/QtStackedBars3D/qbars3d.sip"
#include <QBars3D.h>
#line 26 "sip/QtStackedBars3D/qstackedbars3d.sip"
#include <QStackedBars3D.h>
#line 26 "sip/QtStackedBars3D/qcamera3d.sip"
#include <QCamera3D.h>
#line 26 "sip/QtStackedBars3D/qinputhandler3d.sip"
#include <QInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qlight3d.sip"
#include <QLight3D.h>
#line 26 "sip/QtStackedBars3D/qobject3d.sip"
#include <QObject3D.h>
#line 26 "sip/QtStackedBars3D/qscene3d.sip"
#include <QScene3D.h>
#line 26 "sip/QtStackedBars3D/qtheme3d.sip"
#include <QTheme3D.h>
#line 26 "sip/QtStackedBars3D/qabstractaxis3d.sip"
#include <QAbstractAxis3D.h>
#line 26 "sip/QtStackedBars3D/qabstractgraph3d.sip"
#include <QAbstractGraph3D.h>
#line 26 "sip/QtStackedBars3D/qabstractinputhandler3d.sip"
#include <QAbstractInputHandler3D.h>
#line 26 "sip/QtStackedBars3D/qabstractseries3d.sip"
#include <QAbstractSeries3D.h>
#line 26 "sip/QtStackedBars3D/qabstractdataproxy3d.sip"
#include <QAbstractDataProxy3D.h>
#line 26 "sip/QtStackedBars3D/qbarseries3d.sip"
#include <QBarSeries3D.h>
#line 26 "sip/QtStackedBars3D/qbardataitem3d.sip"
#include <QBarDataItem3D.h>
#line 32 "sip/QtStackedBars3D/qbardataitem3d.sip"
#include <QBarDataItem3D.h>
#line 59 "/trunet/data/volume2/src/QtStackedBars3D/python_lib/QtStackedBars3D/sipQtStackedBars3DQtStackedBar3DVisQBarDataItem3D.cpp"



PyDoc_STRVAR(doc_QtStackedBar3DVis_QBarDataItem3D_setValue, "setValue(self, float)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QBarDataItem3D_setValue(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QBarDataItem3D_setValue(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        float a0;
         ::QtStackedBar3DVis::QBarDataItem3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bf", &sipSelf, sipType_QtStackedBar3DVis_QBarDataItem3D, &sipCpp, &a0))
        {
            sipCpp->setValue(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBarDataItem3D, sipName_setValue, doc_QtStackedBar3DVis_QBarDataItem3D_setValue);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QBarDataItem3D_value, "value(self) -> float");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QBarDataItem3D_value(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QBarDataItem3D_value(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QBarDataItem3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QBarDataItem3D, &sipCpp))
        {
            float sipRes;

            sipRes = sipCpp->value();

            return PyFloat_FromDouble((double)sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBarDataItem3D, sipName_value, doc_QtStackedBar3DVis_QBarDataItem3D_value);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QBarDataItem3D_setRotation, "setRotation(self, float)");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QBarDataItem3D_setRotation(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QBarDataItem3D_setRotation(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        float a0;
         ::QtStackedBar3DVis::QBarDataItem3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "Bf", &sipSelf, sipType_QtStackedBar3DVis_QBarDataItem3D, &sipCpp, &a0))
        {
            sipCpp->setRotation(a0);

            Py_INCREF(Py_None);
            return Py_None;
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBarDataItem3D, sipName_setRotation, doc_QtStackedBar3DVis_QBarDataItem3D_setRotation);

    return NULL;
}


PyDoc_STRVAR(doc_QtStackedBar3DVis_QBarDataItem3D_rotation, "rotation(self) -> float");

extern "C" {static PyObject *meth_QtStackedBar3DVis_QBarDataItem3D_rotation(PyObject *, PyObject *);}
static PyObject *meth_QtStackedBar3DVis_QBarDataItem3D_rotation(PyObject *sipSelf, PyObject *sipArgs)
{
    PyObject *sipParseErr = NULL;

    {
        const  ::QtStackedBar3DVis::QBarDataItem3D *sipCpp;

        if (sipParseArgs(&sipParseErr, sipArgs, "B", &sipSelf, sipType_QtStackedBar3DVis_QBarDataItem3D, &sipCpp))
        {
            float sipRes;

            sipRes = sipCpp->rotation();

            return PyFloat_FromDouble((double)sipRes);
        }
    }

    /* Raise an exception if the arguments couldn't be parsed. */
    sipNoMethod(sipParseErr, sipName_QBarDataItem3D, sipName_rotation, doc_QtStackedBar3DVis_QBarDataItem3D_rotation);

    return NULL;
}


/* Call the instance's destructor. */
extern "C" {static void release_QtStackedBar3DVis_QBarDataItem3D(void *, int);}
static void release_QtStackedBar3DVis_QBarDataItem3D(void *sipCppV, int)
{
    delete reinterpret_cast< ::QtStackedBar3DVis::QBarDataItem3D *>(sipCppV);
}


extern "C" {static void assign_QtStackedBar3DVis_QBarDataItem3D(void *, SIP_SSIZE_T, void *);}
static void assign_QtStackedBar3DVis_QBarDataItem3D(void *sipDst, SIP_SSIZE_T sipDstIdx, void *sipSrc)
{
    reinterpret_cast< ::QtStackedBar3DVis::QBarDataItem3D *>(sipDst)[sipDstIdx] = *reinterpret_cast< ::QtStackedBar3DVis::QBarDataItem3D *>(sipSrc);
}


extern "C" {static void *array_QtStackedBar3DVis_QBarDataItem3D(SIP_SSIZE_T);}
static void *array_QtStackedBar3DVis_QBarDataItem3D(SIP_SSIZE_T sipNrElem)
{
    return new  ::QtStackedBar3DVis::QBarDataItem3D[sipNrElem];
}


extern "C" {static void *copy_QtStackedBar3DVis_QBarDataItem3D(const void *, SIP_SSIZE_T);}
static void *copy_QtStackedBar3DVis_QBarDataItem3D(const void *sipSrc, SIP_SSIZE_T sipSrcIdx)
{
    return new  ::QtStackedBar3DVis::QBarDataItem3D(reinterpret_cast<const  ::QtStackedBar3DVis::QBarDataItem3D *>(sipSrc)[sipSrcIdx]);
}


extern "C" {static void dealloc_QtStackedBar3DVis_QBarDataItem3D(sipSimpleWrapper *);}
static void dealloc_QtStackedBar3DVis_QBarDataItem3D(sipSimpleWrapper *sipSelf)
{
    if (sipIsOwnedByPython(sipSelf))
    {
        release_QtStackedBar3DVis_QBarDataItem3D(sipGetAddress(sipSelf), 0);
    }
}


extern "C" {static void *init_type_QtStackedBar3DVis_QBarDataItem3D(sipSimpleWrapper *, PyObject *, PyObject *, PyObject **, PyObject **, PyObject **);}
static void *init_type_QtStackedBar3DVis_QBarDataItem3D(sipSimpleWrapper *, PyObject *sipArgs, PyObject *sipKwds, PyObject **sipUnused, PyObject **, PyObject **sipParseErr)
{
     ::QtStackedBar3DVis::QBarDataItem3D *sipCpp = 0;

    {
        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, ""))
        {
            sipCpp = new  ::QtStackedBar3DVis::QBarDataItem3D();

            return sipCpp;
        }
    }

    {
        float a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "f", &a0))
        {
            sipCpp = new  ::QtStackedBar3DVis::QBarDataItem3D(a0);

            return sipCpp;
        }
    }

    {
        float a0;
        float a1;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "ff", &a0, &a1))
        {
            sipCpp = new  ::QtStackedBar3DVis::QBarDataItem3D(a0,a1);

            return sipCpp;
        }
    }

    {
        const  ::QtStackedBar3DVis::QBarDataItem3D* a0;

        if (sipParseKwdArgs(sipParseErr, sipArgs, sipKwds, NULL, sipUnused, "J9", sipType_QtStackedBar3DVis_QBarDataItem3D, &a0))
        {
            sipCpp = new  ::QtStackedBar3DVis::QBarDataItem3D(*a0);

            return sipCpp;
        }
    }

    return NULL;
}


static PyMethodDef methods_QtStackedBar3DVis_QBarDataItem3D[] = {
    {SIP_MLNAME_CAST(sipName_rotation), meth_QtStackedBar3DVis_QBarDataItem3D_rotation, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QBarDataItem3D_rotation)},
    {SIP_MLNAME_CAST(sipName_setRotation), meth_QtStackedBar3DVis_QBarDataItem3D_setRotation, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QBarDataItem3D_setRotation)},
    {SIP_MLNAME_CAST(sipName_setValue), meth_QtStackedBar3DVis_QBarDataItem3D_setValue, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QBarDataItem3D_setValue)},
    {SIP_MLNAME_CAST(sipName_value), meth_QtStackedBar3DVis_QBarDataItem3D_value, METH_VARARGS, SIP_MLDOC_CAST(doc_QtStackedBar3DVis_QBarDataItem3D_value)}
};

PyDoc_STRVAR(doc_QtStackedBar3DVis_QBarDataItem3D, "\1QtStackedBar3DVis.QBarDataItem3D()\n"
"QtStackedBar3DVis.QBarDataItem3D(float)\n"
"QtStackedBar3DVis.QBarDataItem3D(float, float)\n"
"QtStackedBar3DVis.QBarDataItem3D(QtStackedBar3DVis.QBarDataItem3D)");


static pyqt5ClassPluginDef plugin_QtStackedBar3DVis_QBarDataItem3D = {
    0,
    0,
    0,
    0
};


sipClassTypeDef sipTypeDef_QtStackedBars3D_QtStackedBar3DVis_QBarDataItem3D = {
    {
        -1,
        0,
        0,
        SIP_TYPE_SUPER_INIT|SIP_TYPE_CLASS,
        sipNameNr_QtStackedBar3DVis__QBarDataItem3D,
        {0},
        &plugin_QtStackedBar3DVis_QBarDataItem3D
    },
    {
        sipNameNr_QBarDataItem3D,
        {14, 255, 0},
        4, methods_QtStackedBar3DVis_QBarDataItem3D,
        0, 0,
        0, 0,
        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0},
    },
    doc_QtStackedBar3DVis_QBarDataItem3D,
    -1,
    sipNameNr_sip_simplewrapper,
    0,
    0,
    init_type_QtStackedBar3DVis_QBarDataItem3D,
    0,
    0,
#if PY_MAJOR_VERSION >= 3
    0,
    0,
#else
    0,
    0,
    0,
    0,
#endif
    dealloc_QtStackedBar3DVis_QBarDataItem3D,
    assign_QtStackedBar3DVis_QBarDataItem3D,
    array_QtStackedBar3DVis_QBarDataItem3D,
    copy_QtStackedBar3DVis_QBarDataItem3D,
    release_QtStackedBar3DVis_QBarDataItem3D,
    0,
    0,
    0,
    0,
    0,
    0,
    0
};
